/* ============================================================
   background.js — service worker (Step 13, extended in Step 31).
   - Performs the secure POST /run to the backend. Doing the fetch
     here (extension-privileged, with host_permissions) avoids the
     page-context CORS restrictions a content script would hit.
   - Step 31: makes the extension a thin client of the SAME backend the
     dashboard panel uses (Model A): it can list saved workflows
     (GET /workflows/:userId), run a saved workflow
     (POST /workflows/:userId/:workflowId/run), open the panel tab, and
     stream a job's live events over SSE — forwarding each event to the
     popup so it can paint per-node tick/error (mirroring Step 26).
   - Relays a few control messages from the popup to the active tab's
     content script (picker/recorder toggles).

   Settings (backend base URL, API key, userId) live in
   chrome.storage.local: ab_baseUrl, ab_apiKey, ab_userId.
   API key is never logged.

   Pure URL/parse/event logic is shared with the popup (and unit tests)
   via lib/ab-core.js — imported here as the global ABCore.
   ============================================================ */
'use strict';

// Service workers can pull in classic scripts synchronously. ab-core.js is a
// pure, DOM-free module that also runs in the popup and in vitest (one source
// of truth for URL building, list parsing and live-event mapping).
try { importScripts('lib/ab-core.js'); } catch (e) { /* ABCore optional fallback below */ }

// ab-handoff.js is the Local half of the Remote <-> Local switch. It lives HERE
// rather than in the popup on purpose: restoring a session opens N tabs and then
// reports completion, and the popup is destroyed the instant the user clicks
// away or Chrome moves focus to a new tab. A restore hosted in the popup would
// be killed mid-sequence, leaving some tabs open, nothing focused and the server
// still waiting -- exactly the "half-moved browser" state the ordering inside
// applyHandoff() is designed to avoid. The worker outlives the popup, so the
// popup only sends a message and the sequence completes regardless.
try { importScripts('lib/ab-handoff.js'); } catch (e) { /* ABHandoff optional; guarded at use */ }

// Optional, and present ONLY in the copy the server side-loads into the REMOTE
// browser (generated by src/core/InspectorExtension.ts). It is absent from the
// authored `extension/` directory and from any hand-installed copy, so the
// failure to import is the normal case for a user's own Chrome — hence a plain
// swallow rather than a warning.
try { importScripts('bootstrap.config.js'); } catch (e) { /* not a managed copy */ }

/**
 * Apply the server's bootstrap settings as DEFAULTS.
 *
 * WHY THIS EXISTS
 * ---------------
 * When the server side-loads this extension into the remote browser, the fresh
 * profile has an EMPTY `chrome.storage.local`. Without this, the popup would open
 * inside a remote desktop asking the user for the address and API token of the
 * very server that just launched the browser they are looking at — something
 * they cannot read from in there, and should not have to.
 *
 * WHY IT CAN ONLY EVER FILL IN BLANKS
 * -----------------------------------
 * Each key is written only when it is currently empty. A user who typed their own
 * base URL or key keeps it, on this launch and on every launch after — a managed
 * default that silently reverted a deliberate setting would be far worse than no
 * default at all. That is also why it is not `chrome.storage.local.set(all)`.
 */
async function applyBootstrapDefaults() {
  if (typeof AB_BOOTSTRAP === 'undefined' || !AB_BOOTSTRAP) return;
  var current = await new Promise(function (resolve) {
    chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
      resolve(s || {});
    });
  });

  var patch = {};
  if (!current.ab_baseUrl && AB_BOOTSTRAP.baseUrl) patch.ab_baseUrl = AB_BOOTSTRAP.baseUrl;
  if (!current.ab_apiKey && AB_BOOTSTRAP.apiKey) patch.ab_apiKey = AB_BOOTSTRAP.apiKey;
  if (!current.ab_userId && AB_BOOTSTRAP.userId) patch.ab_userId = AB_BOOTSTRAP.userId;
  if (!Object.keys(patch).length) return;

  await new Promise(function (resolve) {
    chrome.storage.local.set(patch, function () { resolve(); });
  });
}

// On install AND on every worker start: an MV3 service worker is killed when
// idle, and `onInstalled` does not fire again when it is revived. Running it on
// load as well is what makes the settings reliably present.
if (chrome.runtime && chrome.runtime.onInstalled) {
  chrome.runtime.onInstalled.addListener(function () {
    applyBootstrapDefaults().catch(function () { /* defaults are best-effort */ });
  });
}
var abBootstrapReady = applyBootstrapDefaults().catch(function () { /* best-effort */ });

/**
 * WHICH BROWSER IS THIS EXTENSION RUNNING IN — 'local' or 'remote'?
 *
 * WHY THIS EXISTS
 * ---------------
 * Reported defect: the Remote approval Alert appeared in the operator's OWN
 * Chrome while they were working in LOCAL mode. The binding contract is now:
 *
 *   LOCAL  = the browser runtime on the SAME server as the application.
 *            Nothing to enter — no Base URL, no API Key, no Authorization Code —
 *            and NO Remote Approval Alert. The server resolves its own internal
 *            address and binds the target field itself.
 *   REMOTE = a browser on the server's infrastructure. Its address is resolved
 *            automatically from the server's public configuration, still with no
 *            API Key and no Authorization Code to type, and it is the ONLY
 *            environment that raises the Remote Approval Alert.
 *
 * The prompt is delivered by polling GET /inspector/consent, and that route can
 * only scope by account. Two browsers signed into the SAME account are
 * indistinguishable to it — which is precisely why the server-owned Chrome and
 * the user's Chrome both received the same question. The browser therefore has
 * to say which one it is, and this is that statement.
 *
 * WHY `AB_BOOTSTRAP.managed` IS THE RIGHT SIGNAL
 * ----------------------------------------------
 * `bootstrap.config.js` is GENERATED by src/core/InspectorExtension.ts and
 * copied in only when the server side-loads this extension into the browser it
 * launched itself. It is absent from the authored `extension/` directory and
 * from every hand-installed copy (see the guarded importScripts at the top of
 * this file). So its presence is not a preference and not a heuristic: it is the
 * server's own record of having created this browser. A user's Chrome cannot
 * acquire it by configuring anything, which is what makes the answer
 * unforgeable from the user side.
 *
 * ── WHICH ANSWER THAT PRESENCE MEANS, AND WHY IT FLIPPED ─────────────────────
 * A managed copy means THIS IS THE BROWSER ON THE SERVER, and under the correct
 * naming that browser is `local` — local to the project:
 *
 *   «وقتی لوکال می‌زنم باید مرورگر لوکال سرور بالا بیاید ولی برعکس است»
 *
 * A previous revision returned 'remote' here for exactly the same condition. It
 * was reading the names from the OPERATOR's point of view ("the server is far
 * away from me, so it is remote"), while the server reads them from the
 * project's. Two points of view, one field, opposite answers — which is how the
 * approval prompt ended up gated on the wrong browser.
 *
 * An unmanaged copy — a Chrome the operator installed this into themselves — is
 * `remote`: a machine this server does not own and cannot launch.
 *
 * WHY IT IS NOT THE BACKEND URL
 * -----------------------------
 * The obvious-looking test — "is ab_baseUrl loopback?" — is WRONG and is the
 * conflation this project keeps having to undo. A LOCAL browser is perfectly
 * entitled to drive a REMOTE backend over a public domain:
 *
 *   Backend Base URL   = WHERE THE SERVER IS
 *   Browser Environment = WHICH BROWSER DOES THE PICKING
 *
 * Those are independent, and deciding one from the other is how a local session
 * against a hosted backend ends up classified as remote and gets the Alert.
 *
 * WHY IT DEFAULTS TO 'remote'
 * ---------------------------
 * The failure modes are not symmetric, and the safe default moved with the
 * meaning. The prompt belongs to the server's own shared browser (`local`),
 * because that is the one window that outlives a targeting run and can be
 * holding the previous field's address. So:
 *
 *   Guessing 'local' in an operator's own Chrome would start the approval loop
 *   in a browser that must never run it — it would poll for, and could accept,
 *   prompts raised for a browser it is not. That is the unrecoverable direction.
 *
 *   Guessing 'remote' in the server's browser withholds a prompt. Recoverable:
 *   the operator sees no approval card and can act from the dashboard.
 *
 * So the default is the withholding one, as before — it is only the LABEL that
 * changed sides.
 */
function browserEnvironment() {
  return abBootstrapReady.then(function () {
    try {
      // Seeded by the server = the browser the server launched = LOCAL.
      if (typeof AB_BOOTSTRAP !== 'undefined' && AB_BOOTSTRAP && AB_BOOTSTRAP.managed === true) {
        return 'local';
      }
    } catch (e) { /* fall through to the safe answer */ }
    return 'remote';
  });
}

function getSettings() {
  // Await the bootstrap before reading, so the FIRST request out of a freshly
  // seeded extension is already configured instead of failing with
  // `no_base_url` and needing a retry the user has to guess at.
  return abBootstrapReady.then(function () {
    return new Promise(function (resolve) {
      chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
        resolve({
          baseUrl: (s && s.ab_baseUrl) || '',
          apiKey: (s && s.ab_apiKey) || '',
          userId: (s && s.ab_userId) || 'local'
        });
      });
    });
  });
}

// Prefer the shared ABCore.normalizeBase; keep a tiny local fallback so the
// worker still functions if importScripts ever fails.
function normalizeBase(url) {
  if (typeof ABCore !== 'undefined' && ABCore.normalizeBase) return ABCore.normalizeBase(url);
  var u = String(url || '').trim();
  if (!u) return '';
  if (!/^https?:\/\//i.test(u)) u = 'http://' + u;
  return u.replace(/\/+$/, '');
}

// Small JSON fetch helper that always returns { ok, status, data, error? }.
async function apiFetch(url, opts, apiKey) {
  var headers = Object.assign(
    { 'Content-Type': 'application/json' },
    apiKey ? { 'x-api-key': apiKey } : {},
    (opts && opts.headers) || {}
  );
  try {
    var res = await fetch(url, Object.assign({}, opts, { headers: headers }));
    var text = await res.text();
    var data;
    try { data = text ? JSON.parse(text) : null; } catch (e) { data = { raw: text }; }
    if (!res.ok) return { ok: false, error: 'http_' + res.status, status: res.status, data: data };
    return { ok: true, status: res.status, data: data };
  } catch (e) {
    return { ok: false, error: 'network', message: String((e && e.message) || e) };
  }
}

/* ============================================================================
   ALL BACKEND CALLS BELOW RESOLVE THEIR CONTEXT INTERNALLY.
   ----------------------------------------------------------------------------
   Each of these used to open with the same two lines:

       if (!base)       return { ok: false, error: 'no_base_url' };
       if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };

   Those refusals were the reason the popup had a Base URL box and an API Key
   box: something had to fill the values the worker was demanding. Both
   environments of this product already know their own backend — LOCAL is the
   browser runtime on the same server as the application, REMOTE is side-loaded
   by that server with its address baked into bootstrap.config.js — so the
   demand was asking the user to re-type a value the software already had.

   They now share inspectorContext(), which resolves the address from seeded
   storage, then the bootstrap, then the server-local loopback, and passes the
   API key through when known rather than insisting on it. See its header for
   the full reasoning. The only failure left is one no typing can fix.
   ============================================================================ */

/** Shared guard: resolve the internal context or report the one real failure. */
function contextFailure(ctx) {
  if (ctx && ctx.error) return { ok: false, error: ctx.error };
  return null;
}

// Send the recorded steps to the backend as an inline Flow (POST /run).
async function sendFlow(payload) {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;

  var steps = Array.isArray(payload && payload.steps) ? payload.steps : [];
  if (!steps.length) return { ok: false, error: 'no_steps' };

  var body = { userId: ctx.userId, steps: steps, headless: true };
  if (payload && payload.webhookUrl) body.webhookUrl = payload.webhookUrl;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunInlineUrl)
    ? ABCore.buildRunInlineUrl(ctx.base, { wait: !!(payload && payload.wait) })
    : ctx.base + '/run';
  return apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, ctx.apiKey);
}

// Validate connectivity via GET /me. Returns data so the popup can resolve the
// canonical userId, and reports the resolved backend so the popup can DISPLAY
// the address instead of asking for it.
async function checkConnection() {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;
  var res = await apiFetch(ctx.base + '/me', { method: 'GET' }, ctx.apiKey);
  res.baseUrl = ctx.base;
  res.baseUrlSource = ctx.baseUrlSource;
  return res;
}

// Step 31: list the user's saved workflows — the SAME list the panel shows.
async function listWorkflows() {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;
  var res = await apiFetch(ctx.base + '/workflows/' + encodeURIComponent(ctx.userId), { method: 'GET' }, ctx.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.parseWorkflowList) {
    res.workflows = ABCore.parseWorkflowList(res.data);
  }
  return res;
}

// Step 31: run a saved, versioned workflow (Model B contract, shared with the
// API client) and return the jobId so the popup can subscribe to live events.
async function runSavedWorkflow(payload) {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;
  var workflowId = payload && payload.workflowId;
  if (!workflowId) return { ok: false, error: 'no_workflow_id' };

  var userId = ctx.userId;
  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunSavedUrl)
    ? ABCore.buildRunSavedUrl(ctx.base, userId, workflowId, { wait: !!(payload && payload.wait) })
    : ctx.base + '/workflows/' + encodeURIComponent(userId) + '/' + encodeURIComponent(workflowId) + '/run';

  var body = {};
  if (payload && payload.triggerData) body.triggerData = payload.triggerData;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var res = await apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, ctx.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.extractJobId) {
    res.jobId = ABCore.extractJobId(res.data);
  }
  return res;
}

// ---- Live (SSE) streaming -------------------------------------------------
// We stream a job's events here in the worker (host-privileged) and forward
// each mapped status delta to the popup via runtime messages, so the popup can
// paint tick/error per node even though EventSource cannot set headers.
var liveControllers = {}; // jobId -> AbortController

function broadcast(message) {
  try { chrome.runtime.sendMessage(message, function () { void chrome.runtime.lastError; }); } catch (e) { /* popup closed */ }
}

async function startLive(payload) {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;
  var cfg = { baseUrl: ctx.base, apiKey: ctx.apiKey, userId: ctx.userId };
  var base = ctx.base;
  var jobId = payload && payload.jobId;
  if (!jobId) return { ok: false, error: 'no_job_id' };
  var userId = (payload && payload.userId) || ctx.userId;

  // stop a previous stream for the same job if any
  if (liveControllers[jobId]) { try { liveControllers[jobId].abort(); } catch (e) { /* noop */ } }
  var controller = new AbortController();
  liveControllers[jobId] = controller;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildSseUrl)
    ? ABCore.buildSseUrl(base, userId, jobId, cfg.apiKey)
    : base + '/live/sse/' + encodeURIComponent(userId) + '/' + encodeURIComponent(jobId) + '?api_key=' + encodeURIComponent(cfg.apiKey);

  // Drive the SSE stream with fetch + ReadableStream (works in MV3 workers,
  // unlike EventSource which is unavailable there).
  (async function pump() {
    try {
      var res = await fetch(url, { method: 'GET', signal: controller.signal });
      if (!res.ok || !res.body) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'http_' + res.status });
        cleanupLive(jobId);
        return;
      }
      var reader = res.body.getReader();
      var decoder = new TextDecoder();
      var buf = '';
      while (true) {
        var chunk = await reader.read();
        if (chunk.done) break;
        buf += decoder.decode(chunk.value, { stream: true });
        var idx;
        // SSE frames are separated by a blank line.
        while ((idx = buf.indexOf('\n\n')) !== -1) {
          var frame = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          handleSseFrame(jobId, frame);
        }
      }
      broadcast({ type: 'AB_LIVE_END', jobId: jobId });
    } catch (e) {
      if (!controller.signal.aborted) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'network', message: String((e && e.message) || e) });
      }
    } finally {
      cleanupLive(jobId);
    }
  })();

  return { ok: true, jobId: jobId };
}

function handleSseFrame(jobId, frame) {
  // Parse the "event:" and "data:" lines of one SSE frame.
  var lines = frame.split('\n');
  var dataLines = [];
  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (line.indexOf('data:') === 0) dataLines.push(line.slice(5).trimStart());
  }
  if (!dataLines.length) return;
  var raw = dataLines.join('\n');
  var ev;
  try { ev = JSON.parse(raw); } catch (e) { return; }

  var status = (typeof ABCore !== 'undefined' && ABCore.mapLiveEventToStatus)
    ? ABCore.mapLiveEventToStatus(ev) : null;
  broadcast({ type: 'AB_LIVE_EVENT', jobId: jobId, event: ev, status: status });

  if (typeof ABCore !== 'undefined' && ABCore.isTerminalEvent && ABCore.isTerminalEvent(ev)) {
    var ctrl = liveControllers[jobId];
    if (ctrl) { try { ctrl.abort(); } catch (e) { /* noop */ } }
  }
}

function cleanupLive(jobId) {
  if (liveControllers[jobId]) { delete liveControllers[jobId]; }
}

function stopLive(payload) {
  var jobId = payload && payload.jobId;
  if (jobId && liveControllers[jobId]) {
    try { liveControllers[jobId].abort(); } catch (e) { /* noop */ }
    cleanupLive(jobId);
  }
  return { ok: true };
}

// Step 31: open (or focus) the dashboard panel — the SAME UI the extension is
// a thin client of.
async function openPanel() {
  var ctx = await inspectorContext();
  var bad = contextFailure(ctx);
  if (bad) return bad;
  var base = ctx.base;
  var url = (typeof ABCore !== 'undefined' && ABCore.buildPanelUrl) ? ABCore.buildPanelUrl(base) : base + '/';
  return new Promise(function (resolve) {
    chrome.tabs.create({ url: url }, function (tab) {
      if (chrome.runtime.lastError) { resolve({ ok: false, error: 'open_failed' }); return; }
      resolve({ ok: true, tabId: tab && tab.id });
    });
  });
}

/* ============================================================
   ELEMENT INSPECTOR

   The content script cannot POST the pick itself: a fetch from page context is
   subject to the page's CSP and to CORS against the backend origin. The worker
   holds host_permissions, so the request belongs here — same reason sendFlow
   lives here.

   THE DESTINATION IS A TARGET FIELD, AND IT IS BOUND ONCE
   ------------------------------------------------------
   This worker used to mint its own `ext-…` session id and submit picks under it.
   The dashboard claimed nodes under a per-TAB `ui-…` id, and the server compared
   the two for equality — two independently generated strings, so every pick was
   refused. The id was then read back from the server purely to satisfy the
   comparison, a round trip that carried no information: the value sent was the
   value the server had handed over moments earlier.

   That whole mechanism is gone. The destination is now a Target Field the
   project registers, addressed by `targetFieldId`, and this extension is bound
   to it ONCE — by the SERVER, not by the user:

     LOCAL  the server binds the field internally when the crosshair is used.
            Nothing is typed and nothing is shown to approve.
     REMOTE the server raises an approval request; answering it delivers the
            target (see consentDecide). Still nothing is typed.

   After the binding, ordinary sends carry only the id and whatever key the
   bootstrap supplied — no session, no echo, nothing to keep in sync.

   The extension therefore stores exactly one new thing: which Target Field it is
   currently sending to. It is persisted rather than re-derived so it survives
   worker restarts (MV3 kills workers aggressively).
   ============================================================ */

/**
 * Resolve the backend context for the inspector calls — WITHOUT asking the user.
 *
 * WHAT THIS USED TO DO, AND WHY IT WAS THE DEFECT
 * ----------------------------------------------
 * It read `ab_baseUrl` and `ab_apiKey` out of storage and, if either was blank,
 * refused with `no_base_url` / `no_api_key`. Those two strings were the engine
 * of the whole reported problem: the popup rendered them as "set the Base URL
 * first" / "set the API Key first", which is why it HAD a Base URL box and an
 * API key box at all. Every credential control in the extension existed to
 * satisfy this function.
 *
 * That is backwards for both environments of this product:
 *
 *   LOCAL BROWSER  = the browser runtime on the SAME server the application runs
 *                    on. The backend is not merely reachable from here, it is the
 *                    process that launched this browser. Its address is internal
 *                    and known; there is nothing for a human to look up.
 *   REMOTE BROWSER = the browser on the server's own infrastructure, side-loaded
 *                    with this extension by that same server, which wrote its own
 *                    public address and token into bootstrap.config.js on the way
 *                    in (src/core/InspectorExtension.ts).
 *
 * In both cases the server is the authority on its own address and token, and it
 * has already stated both. Asking the user to retype them was asking them to
 * re-supply — by hand, from inside a browser they may not be able to read them
 * from — values that were present and correct all along.
 *
 * WHAT IT DOES NOW
 * ----------------
 * Three internal sources, in order of authority, and no user input anywhere:
 *
 *   1. Storage, which `applyBootstrapDefaults()` has already seeded from the
 *      server's own bootstrap. This is the normal case and it is exact.
 *   2. `AB_BOOTSTRAP` directly, in case storage was cleared after seeding — the
 *      generated file is still importable, so the answer is still available.
 *   3. The server-local loopback default. Reached only when there is no bootstrap
 *      at all, which is a hand-installed copy driving a server on this machine.
 *      This is a guess, but it is the RIGHT guess for exactly the case that has
 *      no other source, and it is the same address the server publishes to its
 *      own managed copies (InspectorExtension.serverBaseUrl()).
 *
 * The API key is passed through when known and OMITTED when not — never demanded.
 * `apiFetch()` already sends no `x-api-key` header for an empty value, and a
 * server-local request without one is a request the backend is entitled to
 * accept or refuse on its own terms. Refusing it HERE, before it is made, is the
 * behaviour that produced a credential form.
 *
 * The single remaining failure is `runtime_context_unavailable`, and it means
 * something the user genuinely cannot fix by typing: no address could be
 * resolved from any internal source. The popup says so in those terms.
 */
/**
 * The port to assume when NOTHING has told us better.
 *
 * A last resort, and it is a genuine guess — which is why the seeded bootstrap
 * carries the real one (`AB_BOOTSTRAP.port`) and is preferred over this. It used
 * to be baked into a hardcoded `http://127.0.0.1:3000` constant, so a server
 * started with `PORT=8080` seeded a browser that talked to nothing and reported
 * a network error the operator could do nothing about:
 *
 *   «روی 127.0.0.1:پورت پروژه که بالا آمده رو خودش ست کنه»
 */
var LOOPBACK_PORT_FALLBACK = 3000;

/** Build the server-local address for a port. LOCAL environment only. */
function loopbackBase(port) {
  var n = parseInt(port, 10);
  if (!isFinite(n) || n <= 0 || n > 65535) n = LOOPBACK_PORT_FALLBACK;
  return 'http://127.0.0.1:' + n;
}

async function inspectorContext() {
  var cfg = await getSettings();

  // 1 — what the server seeded (or what a previous version stored).
  var base = normalizeBase(cfg.baseUrl);
  var apiKey = cfg.apiKey || '';
  var userId = cfg.userId || 'local';
  var source = base ? 'bootstrap' : '';

  // 2 — the generated bootstrap itself, if storage lost it.
  if (!base || !apiKey) {
    try {
      if (typeof AB_BOOTSTRAP !== 'undefined' && AB_BOOTSTRAP) {
        if (!base && AB_BOOTSTRAP.baseUrl) {
          base = normalizeBase(AB_BOOTSTRAP.baseUrl);
          source = 'bootstrap';
        }
        if (!apiKey && AB_BOOTSTRAP.apiKey) apiKey = AB_BOOTSTRAP.apiKey;
        if ((!userId || userId === 'local') && AB_BOOTSTRAP.userId) userId = AB_BOOTSTRAP.userId;
      }
    } catch (e) { /* not a managed copy — fall through to the loopback default */ }
  }

  // 3 — the server-local default. The LOCAL contract is "the browser runtime on
  //     the same server", so loopback is not a fallback in spirit: it IS the
  //     address of a server-local backend, and it is what the server itself
  //     publishes to the copies it seeds.
  //
  //     The PORT comes from the seeded bootstrap when there is one, so this
  //     tracks the port the server actually listens on instead of assuming the
  //     default. Only a copy that was never seeded falls back to the guess.
  if (!base) {
    var seededPort = 0;
    try {
      if (typeof AB_BOOTSTRAP !== 'undefined' && AB_BOOTSTRAP && AB_BOOTSTRAP.port) {
        seededPort = AB_BOOTSTRAP.port;
      }
    } catch (e) { /* unmanaged copy — the guess below is all there is */ }
    base = normalizeBase(loopbackBase(seededPort));
    source = 'server-local';
  }

  if (!base) return { error: 'runtime_context_unavailable' };

  // `apiKey` may legitimately be '' here. That is not an error state: it is a
  // request the backend gets to judge, and the alternative — refusing to ask —
  // is what put an API key box on screen.
  return { base: base, apiKey: apiKey, userId: userId, baseUrlSource: source };
}

/** Which Target Field this extension is currently sending to, if any. */
function getTargetFieldId() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_targetFieldId'], function (s) {
      resolve((s && s.ab_targetFieldId) || '');
    });
  });
}

function setTargetFieldId(id) {
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_targetFieldId: id || '' }, function () { resolve(id || ''); });
  });
}

/**
 * The STABLE identity of the field this extension is paired with.
 *
 * Stored ALONGSIDE the address, not instead of it, because the two have
 * different lifetimes and answer different questions:
 *
 *   ab_targetFieldId  — the ADDRESS. Re-minted whenever the node is re-opened,
 *                       expires in hours. Says WHERE a pick should be sent.
 *   ab_pairingKey     — the IDENTITY. Derived from workflow+node+field, expires
 *                       in days. Says WHETHER this extension is trusted for
 *                       that field at all.
 *
 * Keeping only the address is what used to make a binding look temporary: the
 * address died on the next NDV open, and with nothing durable stored the popup
 * had to report "not bound" and the operator was asked to authorize again. The
 * original requirement was explicit that a re-authorization must not be needed
 * for the same extension and the same target field, and that still holds under
 * the current contract — where re-authorizing would mean re-approving a REMOTE
 * request, and for LOCAL would mean nothing at all.
 */
function getPairingKey() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_pairingKey'], function (s) {
      resolve((s && s.ab_pairingKey) || '');
    });
  });
}

function setPairingKey(key) {
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_pairingKey: key || '' }, function () { resolve(key || ''); });
  });
}

/**
 * Which BROWSER ENVIRONMENT the field this extension is paired with was
 * targeted in — 'local' or 'remote'.
 *
 * Recorded so the popup can state it rather than leave the operator guessing,
 * and read from the SERVER's target record, never asserted by the extension.
 * It is a third, separate concept from both of the ids above and from the
 * automation Browser Mode:
 *
 *   Browser Environment = LOCAL / REMOTE   (which browser the pick happens in)
 *   Session / Handoff   = as_… remote infra (not involved here at all)
 *   targetFieldId       = the destination   (where the value lands)
 *
 * The popup's CONNECTION tab shows a local/remote pair too, but that is derived
 * from whether the BACKEND URL is loopback — where the server is, not which
 * browser is doing the targeting. Conflating them is the confusion this field
 * exists to end.
 */
function getTargetEnvironment() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_targetEnvironment'], function (s) {
      resolve((s && s.ab_targetEnvironment) || '');
    });
  });
}

function setTargetEnvironment(env) {
  var v = (env === 'local' || env === 'remote') ? env : '';
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_targetEnvironment: v }, function () { resolve(v); });
  });
}

/**
 * What is this extension attached to — which mode, which fields are open, and
 * which of them may it write to?
 *
 * Asked when the popup opens, so the user sees the answer before picking rather
 * than discovering it from a failed send. `authorized` comes back scoped to THIS
 * API key, so the popup can show "connected to this Field" truthfully instead of
 * listing fields the extension cannot actually reach.
 */
async function inspectorSession() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var res = await apiFetch(ctx.base + '/inspector/session', { method: 'GET' }, ctx.apiKey);
  var data = (res && res.data) || {};
  var chosen = await getTargetFieldId();

  // The address this request actually used, reported back so the popup can SHOW
  // the resolved backend instead of echoing an input box. Sent on failure too —
  // "cannot reach X" is only actionable if X is named. `baseUrlSource` says
  // whether it came from the server's bootstrap or the server-local default,
  // which is the difference between a managed browser and a hand-installed one.
  res.baseUrl = ctx.base;
  res.baseUrlSource = ctx.baseUrlSource;

  var authorized = data.authorized || [];
  var isAuthorized = authorized.some(function (b) { return b.targetFieldId === chosen; });

  res.targetFieldId = chosen;
  res.authorized = isAuthorized;
  // The full record for the DESTINATION panel: node name, field name, label.
  var target = (data.targets || []).filter(function (t) {
    return t.targetFieldId === chosen;
  })[0] || null;
  res.target = target;

  // ── The durable half of the answer ───────────────────────────────────────
  //
  // The stored pairing key is preferred over the live target's, because the
  // point of a pairing is that it outlives the address: when the dashboard has
  // not re-registered the field yet, `target` is null and the address is stale,
  // yet the operator must still be told they are paired and will NOT be asked
  // for another code.
  var storedKey = await getPairingKey();
  var pairingKey = storedKey || (target && target.pairingKey) || '';
  var pairings = data.pairings || [];
  res.pairingKey = pairingKey;
  res.paired = !!pairingKey && pairings.some(function (p) {
    return p && p.pairingKey === pairingKey;
  });

  // Environment is taken from the SERVER's target record — the extension does
  // not get to assert which browser it is. The stored value is only a fallback
  // for when the field is not currently registered.
  var env = (target && target.environment) || (await getTargetEnvironment());
  res.environment = (env === 'local' || env === 'remote') ? env : '';
  if (target && target.environment) await setTargetEnvironment(target.environment);

  // A pairing the server no longer holds must not keep being displayed: the
  // operator would be told no code is needed and then be refused on send.
  if (pairingKey && !res.paired && pairings.length) await setPairingKey('');
  return res;
}

/**
 * WHAT THE TWO ENVIRONMENTS ACTUALLY MEAN.
 *
 * This block used to claim "inspectorPair() IS DELETED" and that REMOTE meant
 * "the server's own browser". Both statements were false, and the second was the
 * original LOCAL/REMOTE inversion surviving in prose after the code had been
 * corrected. inspectorPair() is defined below and IS routed (AB_INSPECTOR_PAIR).
 * Stale prose that contradicts adjacent code is not a harmless leftover: it is
 * how the inversion got re-introduced once already, because the next reader
 * trusts the comment over the call graph.
 *
 *   LOCAL BROWSER  — the Project and the browser are on the SAME customer
 *                    server. The address is therefore something the PROJECT
 *                    knows and sets; the operator has nothing to type. There is
 *                    NO authorization code in LOCAL — not a field for one, not a
 *                    generate button, not a refresh. When the field identity the
 *                    extension holds does not match the field the project is
 *                    targeting (MISMATCH, which includes holding nothing at
 *                    all), the server raises a confirmation prompt and the
 *                    operator approves it — see consentDecide() below.
 *
 *   REMOTE BROWSER — the browser is on the OPERATOR'S OWN machine, reaching a
 *                    server somewhere else. Nothing can resolve that address for
 *                    them, so the Base URL is fully theirs to set: a different
 *                    IP, domain or port per install. Authorization exists here,
 *                    and only here, and is minted only on MISMATCH.
 *
 * The deciding criterion in BOTH environments is field identity — MATCH versus
 * MISMATCH — and never "did something change". A matching field needs no prompt
 * and no new code, because the extension is already pointed where the project
 * wants it. See syncDecision() in src/core/FieldIdentity.ts for the single
 * comparison both branches consult.
 *
 * consentDecide() and inspectorPair() are the two ways a target lands in storage,
 * and they are worth comparing — same outcome, reached by ANSWERING a question
 * the server asked (LOCAL) versus transcribing a secret the server minted
 * (REMOTE).
 */

/**
 * Forget the binding locally.
 *
 * Clears the durable key as well as the address — otherwise the popup would go
 * on reporting "bound" for a field this extension has deliberately let go of.
 * The server keeps its own record until the dashboard's explicit
 * `/inspector/targeting/unpair`; this is the extension's local half.
 */
async function inspectorUnpair() {
  await setTargetFieldId('');
  await setPairingKey('');
  await setTargetEnvironment('');
  return { ok: true };
}

/* ============================================================
   REMOTE TARGETING CONSENT
   ============================================================

   WHY THIS EXISTS

   The browser running on the server is, from this extension's point of view, an
   ordinary LOCAL browser. It loads this same code, and it addresses a submit
   with `ab_targetFieldId` out of chrome.storage.local.

   Historically the ONLY writer of that value was inspectorPair(), which redeemed
   an Authorization Code — a mechanism since removed entirely. REMOTE never issued
   a code even then, by explicit requirement, so on the remote path the value
   stayed empty, submitElement() refused locally with TARGET_NOT_AUTHORIZED before
   any HTTP request was made, and the operator saw:

     «ظاهرا نمیدونه به کدوم فیلد باید ارسال بشه» — Connection failed: network

   The server had granted a binding. Nothing had ever told the CLIENT which field
   it was for.

   WHY A PROMPT AND NOT AN AUTO-FILL

   The obvious shortcut is to have the extension ask "what is my current target?"
   and adopt the answer. That was rejected: with two nodes open there IS no
   single current target, and picking the most recent silently means a pick lands
   in the node the operator is no longer looking at, WITH a success message. That
   is strictly worse than the refusal it replaces, because a refusal is visible.
   It also breaks the standing rule «The Extension must NEVER be able to choose
   an arbitrary Target Field» — an extension that adopts whatever a list contains
   has chosen.

   So the server ASKS, naming the node and the field, and the human answers. A
   consent and a code are the same security object — one-time, server-issued,
   expiring, single-target, completable only by a person. The consent is merely
   addressed to a browser the server can already reach, so it can be DELIVERED
   instead of TRANSCRIBED. Approval is what attaches the destination, which is
   why the reply to a decision is stored exactly the way a redeemed code is.
   ============================================================ */

/**
 * What is this browser being asked to confirm?
 *
 * Returns the human-readable questions ONLY. The server withholds the target
 * address from this list on purpose (see ConsentPrompt in
 * src/core/RemoteTargetConsent.ts): if the address were here, this function
 * could store it and skip the prompt, which is the one thing the handshake
 * exists to prevent.
 */
async function consentList(sender) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error, requests: [] };

  var env = await browserEnvironment();

  // ── ONE PENDING REQUEST, ONE ACTIVE TAB, ONE ALERT ─────────────────────
  //
  // REPORTED, with three tabs open in the Local Browser and only the third
  // one visible:
  //
  //   «Tab 1 — [Picker Alert] / Tab 2 — [Picker Alert] / Tab 3 — [Picker Alert]
  //    … هر Tab نباید independently همان pending picker request را render کند.»
  //
  // ROOT CAUSE. consent.js is a content script, so there is one copy of it per
  // tab, and each copy polled this function on its own clock. This function
  // answered every caller with the same list, so N tabs drew N copies of one
  // question. `document.hidden` in the page could not fix it: MEASURED over
  // CDP in the running browser, all three tabs of one window reported
  // `visibilityState === 'visible'` while `chrome.tabs` reported exactly one
  // `active: true`. The page cannot tell whether it is the tab the operator is
  // looking at; the service worker can.
  //
  // So OWNERSHIP is decided HERE, once, by the only component that has the
  // whole browser in view. The request belongs to the active tab of the
  // focused window and to nothing else. A non-owner is told so explicitly
  // (`owner: false`) rather than being handed an empty list it might read as
  // "nothing pending": consent.js uses that flag to CLOSE a dialog it may
  // still be showing from when it WAS the owner, so a tab switch moves the
  // Alert instead of copying it. See consentOwnershipChanged() for the push
  // that makes the hand-over immediate rather than one poll tick late.
  var owner = await isConsentOwner(sender);
  if (!owner) {
    return { ok: true, count: 0, requests: [], environment: env, owner: false, skipped: 'not_active_tab' };
  }

  // A REMOTE browser — one on the operator's own machine — is answered here and
  // never asks the server.
  //
  // THE DIRECTION OF THIS GATE FLIPPED WITH THE NAMES. The approval prompt
  // belongs to the SERVER's own browser (`local`), because that is the single
  // shared window which outlives a targeting run and may still be holding the
  // previous field's address. A browser on the operator's desktop acquires its
  // target by redeeming an Authorization Code, which named exactly one field, so
  // there is nothing left for it to be asked.
  //
  // This is the FIRST of two independent gates, and the reason there are two is
  // that they fail differently. The server-side filter (pendingFor) protects a
  // browser running a CURRENT extension against a server that has a prompt
  // outstanding for the other environment. This one protects against the server
  // too: an older backend, a backend that has not been redeployed, or any future
  // route that forgets the filter, still cannot produce an Alert in the
  // operator's own browser, because there the request is not made at all.
  //
  // Returning `ok: true` with an empty list rather than an error is deliberate:
  // "nothing is pending for you" is the TRUTH here, because a REMOTE browser's
  // binding was completed by the redemption — a path that is complete on its own
  // and needs no prompt, no polling and no timeout. An error would make callers
  // back off and retry as if something were broken.
  if (env !== 'local') {
    return { ok: true, count: 0, requests: [], environment: env, skipped: 'remote' };
  }

  // Declared BOTH ways on purpose. The query string is what the route reads
  // first and is visible in a server log when diagnosing exactly this class of
  // bug; the header survives a proxy that rewrites or strips query strings.
  // src/Routes/mode.routes.ts accepts either and treats them identically.
  var res = await apiFetch(
    ctx.base + '/inspector/consent?environment=' + encodeURIComponent(env),
    { method: 'GET', headers: { 'x-browser-environment': env } },
    ctx.apiKey
  );
  var data = (res && res.data) || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'Could not ask the server what is pending.',
      requests: [],
      environment: env,
    };
  }
  return {
    ok: true,
    owner: true,
    count: data.count || 0,
    requests: data.requests || [],
    environment: env,
  };
}

/**
 * WHICH TAB OWNS THE ALERT?
 *
 * The active tab of the last-focused window, and only that. `sender` is the
 * `chrome.runtime.onMessage` sender, whose `.tab` is the tab the content
 * script lives in — a value Chrome fills in itself, so a page cannot claim to
 * be a tab it is not.
 *
 * Decided per call rather than cached: a cached owner would go stale on the
 * very tab switch this exists to track. `lastFocusedWindow` rather than
 * `currentWindow`: in a service worker there is no "current" window, and the
 * documented meaning of currentWindow there is undefined.
 *
 * No sender tab (the popup, or a worker-internal call) is NOT an owner: the
 * Alert is drawn in a page, so only a page can hold it.
 */
function isConsentOwner(sender) {
  return new Promise(function (resolve) {
    var tabId = sender && sender.tab && sender.tab.id;
    if (tabId == null) { resolve(false); return; }
    try {
      chrome.tabs.query({ active: true, lastFocusedWindow: true }, function (tabs) {
        if (chrome.runtime.lastError) { resolve(false); return; }
        var t = tabs && tabs[0];
        if (t) { resolve(t.id === tabId); return; }
        // No focused window at all (the operator is in another application).
        // The active tab of the sender's OWN window is then the one they will
        // see first when they come back, so it keeps the request rather than
        // the request being orphaned until focus returns.
        chrome.tabs.query({ active: true, windowId: sender.tab.windowId }, function (own) {
          if (chrome.runtime.lastError) { resolve(false); return; }
          var o = own && own[0];
          resolve(!!(o && o.id === tabId));
        });
      });
    } catch (e) {
      resolve(false);
    }
  });
}

/**
 * The operator switched tabs (or windows): tell the OLD owner to stand down
 * and the NEW owner to ask now.
 *
 * Without this push the hand-over would still happen — the old tab's next
 * poll answers `owner:false` and it closes, the new tab's next poll draws —
 * but "next poll" is up to 4s (20s when idle), and for that window BOTH tabs
 * would show the Alert, which is exactly the duplicate the operator
 * described:
 *
 *   «A نباید Alert قابل مشاهده داشته باشد / B نباید یک Alert duplicate بسازد»
 *
 * So the transition is made DETERMINISTIC: close-then-draw, in that order,
 * driven by Chrome's own activation event. Tabs without the content script
 * (chrome://, about:blank, the extension's own pages) simply fail the
 * sendMessage, which is swallowed — there is nothing there to close.
 */
var lastConsentOwnerTabId = null;

function tellTab(tabId, msg) {
  if (tabId == null) return;
  try {
    chrome.tabs.sendMessage(tabId, msg, function () {
      // Read lastError so Chrome does not log "Unchecked runtime.lastError".
      void chrome.runtime.lastError;
    });
  } catch (e) { /* tab gone, or no content script — nothing to tell */ }
}

function consentOwnershipChanged(newTabId) {
  if (newTabId == null || newTabId === lastConsentOwnerTabId) return;
  var previous = lastConsentOwnerTabId;
  lastConsentOwnerTabId = newTabId;
  // The old owner FIRST, so at no instant are two dialogs open on purpose.
  if (previous != null) tellTab(previous, { type: 'AB_CONSENT_OWNER_CHANGED', owner: false });
  tellTab(newTabId, { type: 'AB_CONSENT_OWNER_CHANGED', owner: true });
}

if (chrome.tabs && chrome.tabs.onActivated) {
  chrome.tabs.onActivated.addListener(function (info) {
    if (info && info.tabId != null) consentOwnershipChanged(info.tabId);
  });
}
if (chrome.windows && chrome.windows.onFocusChanged) {
  chrome.windows.onFocusChanged.addListener(function (windowId) {
    if (windowId === chrome.windows.WINDOW_ID_NONE) return;
    try {
      chrome.tabs.query({ active: true, windowId: windowId }, function (tabs) {
        if (chrome.runtime.lastError) return;
        var t = tabs && tabs[0];
        if (t && t.id != null) consentOwnershipChanged(t.id);
      });
    } catch (e) { /* no windows API in this context */ }
  });
}

/**
 * The human pressed Allow (or Deny).
 *
 * Sends a `consentId` and a boolean — never a target. The destination comes back
 * FROM the server, decided before the prompt was ever raised, and storing it is
 * the line that makes the reported failure go away: it is the write to
 * `ab_targetFieldId` that REMOTE never had.
 *
 * Stores the durable pairing key and the environment alongside the target, so a
 * consent-granted binding survives an NDV reopen. If it did not, the operator
 * would be re-prompted every time and "click Allow every time" would simply be
 * a new spelling of the defect this work removes.
 *
 * ── WHICH BROWSER THIS BELONGS TO, AND THE CONTRADICTION IT RESOLVES ────────
 *
 * It applies to LOCAL alone — the browser runtime on the SAME server as the
 * project. That window is one shared, long-lived browser: it outlives a single
 * targeting run and may still be holding the previous field's address, so a
 * human has to say which of them the next pick belongs to. The Alert names the
 * node and the field, and pressing Allow is what writes `ab_targetFieldId`.
 *
 * REMOTE needs no counterpart. A browser on the operator's own machine acquires
 * its destination by redeeming an Authorization Code, and that code named
 * exactly one Target Field — so there is nothing left to be asked.
 *
 * THIS GATE POINTED THE OTHER WAY, AND THAT WAS A LIVE DEFECT, not merely a
 * stale comment. consentList() above admits `local` and turns `remote` away;
 * this one admitted `remote` and turned `local` away. The two together meant a
 * LOCAL browser could SEE the Alert and then be refused the moment it pressed
 * Allow — `wrong_environment` on the one environment that actually raises the
 * prompt, and no binding written at all. The old name `needsRemoteApproval` is
 * what let the pair read as consistent while they disagreed.
 */
async function consentDecide(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var consentId = String((payload && payload.consentId) || '').trim();
  if (!consentId) {
    return { ok: false, reason: 'consent_not_found', error: 'Nothing to answer.' };
  }

  // A REMOTE browser cannot complete this grant, even if a consentId reaches it
  // somehow (a stale card left in a tab from an earlier LOCAL session, or a page
  // that guesses an id). Gating the LIST alone would leave the write to
  // `ab_targetFieldId` reachable, and that write is the whole point of the
  // handshake. A browser on the operator's own machine has no business answering
  // it because it never needed to: its field arrived with the Authorization Code
  // it redeemed, which is why the Alert is a LOCAL-only surface.
  //
  // MIRRORS consentList() EXACTLY — admit `local`, refuse everything else — and
  // that symmetry is the fix. While this said `remote`, the two gates disagreed
  // and the server's own browser was shown a prompt it was then forbidden to
  // answer.
  var env = await browserEnvironment();
  if (env !== 'local') {
    return {
      ok: false,
      reason: 'wrong_environment',
      // Names the path that DOES apply here, because a refusal the operator
      // cannot act on is only half an answer.
      error: 'This approval belongs to the browser running on the server. '
        + 'To connect a browser on your own machine, use the Authorization Code '
        + 'from the dashboard (Target This Field → Remote Browser).',
      environment: env,
    };
  }
  // Explicitly boolean: `approve: undefined` must never read as approval.
  var approve = (payload && payload.approve) === true;

  var res = await apiFetch(
    ctx.base + '/inspector/consent/decide',
    { method: 'POST', body: JSON.stringify({ consentId: consentId, approve: approve }) },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'That request could not be answered.',
    };
  }

  // Denied: the server attached nothing, so neither do we. Anything already
  // paired is left alone — declining a NEW field must not disconnect the field
  // this browser is currently working on.
  if (!data.approved) {
    return { ok: true, approved: false, consentId: consentId };
  }

  var target = data.target || null;
  var id = (data.binding && data.binding.targetFieldId) || data.targetFieldId
    || (target && target.targetFieldId) || '';
  await setTargetFieldId(id);

  var pairingKey = (data.binding && data.binding.pairingKey) || data.pairingKey
    || (target && target.pairingKey) || '';
  await setPairingKey(pairingKey);

  // Reuses the `env` declared above (a second `var env` here was a duplicate
  // declaration that silently shadowed nothing and only confused readers).
  //
  // The fallback is `local`, not `remote`: reaching this line at all means the
  // gate above admitted this browser, and it admits `local` only. A `remote`
  // default would have stamped the one environment that can never get here.
  env = (target && target.environment) || 'local';
  await setTargetEnvironment(env);

  return {
    ok: true,
    approved: true,
    consentId: consentId,
    targetFieldId: id,
    pairingKey: pairingKey,
    environment: env,
    target: target,
  };
}

/**
 * Deliver ONE confirmed attribute to the paired Target Field.
 *
 * §21: «the system sends exactly ONE Radio-selected value», so the payload
 * carries `sendAttribute` (the radio) and `displayAttributes` (the checkboxes,
 * which affect display only). The server recomputes the value from the element
 * it receives, so the `value` here is advisory.
 *
 * Refusals pass the backend's §27 code and sentence through UNCHANGED, because
 * "this Inspector is not authorized for that Field" is a fixable problem and a
 * generic failure message hides the fix.
 */
async function submitElement(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var element = payload && payload.element;
  if (!element) return { ok: false, error: 'no_element' };

  // §22.5 — a radio must be selected. Refused here rather than sent, because the
  // only possible answer is a 409 and the message is the same either way.
  var send = (payload && payload.sendAttribute) || null;
  var attrName = send && String(send.name || '').trim();
  if (!attrName) {
    return {
      ok: false,
      reason: 'ATTRIBUTE_SEND_FAILED',
      error: 'Select one attribute to send.'
    };
  }

  // The destination must have been bound. Refusing locally saves a round trip
  // and names the actual fix — which is now an action in the PROJECT, not a
  // credential to type here. Was: 'Enter an Authorization Code first.'
  var targetFieldId = await getTargetFieldId();
  if (!targetFieldId) {
    return {
      ok: false,
      reason: 'TARGET_NOT_AUTHORIZED',
      error: 'This Inspector is not bound to a Field yet. In the project, click the '
        + 'crosshair on the field you want to fill (and approve the request if this '
        + 'is the remote browser).'
    };
  }

  var res = await apiFetch(
    ctx.base + '/inspector/element',
    {
      method: 'POST',
      body: JSON.stringify({
        targetFieldId: targetFieldId,
        element: element,
        displayAttributes: (payload && payload.displayAttributes) || [],
        sendAttribute: { name: attrName, value: send.value }
      })
    },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'The element could not be delivered.',
      targets: data.targets || []
    };
  }

  // §24: the confirmation NAMES the field, the attribute and the value — that is
  // what proves the value did not silently go somewhere else.
  return {
    ok: true,
    node: data.nodeName || '',
    field: data.fieldName || '',
    targetFieldId: data.targetFieldId || targetFieldId,
    attribute: data.attribute || attrName,
    value: data.value || '',
    delivery: data.delivery || null
  };
}

/* ============================================================================
   BROWSER ENVIRONMENT — THE LOCAL / REMOTE CHOICE, FROM INSIDE THE EXTENSION
   ----------------------------------------------------------------------------
   REPORTED, and the regression these two functions repair:

     «UI فعلی دیگر هیچ انتخابی برای LOCAL BROWSER / REMOTE BROWSER ندارد. طبق
      قرارداد نهایی، این انتخاب باید حتماً در Targeting flow باقی بماند. این را
      با Backend Connection اشتباه نکن.»

   The choice itself was never deleted from the product: the dashboard's own
   dialog (public/js/targeting-flow.js renderChooser) still offers both cards.
   What was missing is that the choice existed ONLY there. An operator working
   from the extension popup — which is where "Target this field" is reached in
   the browser being targeted — had no way to make it, so the environment was
   whatever the last dashboard interaction happened to record.

   WHAT THESE ARE NOT
   ------------------
   Not the Backend Connection. That is WHERE THE SERVER IS, it is resolved by
   the server, it is not a choice, and the controls that used to ask for it
   (#baseUrl, #apiKey, the Local/Remote BACKEND radio pair) are deleted and stay
   deleted. These two functions carry the third, separate concept:

     Browser Environment  LOCAL / REMOTE   <- WHICH BROWSER does the picking
     Backend location     resolved by the server, never asked
     targetFieldId        the destination, minted server-side

   NO NEW BACKEND. Both call the routes the dashboard chooser already calls,
   unchanged: GET /inspector/targeting/options and POST /inspector/targeting/
   begin. There is deliberately no new endpoint, no new grant path and no new
   binding rule — the server keeps deciding all of that, exactly as it does for
   the dashboard, which is what stops the two surfaces from disagreeing.
   ========================================================================== */

/**
 * Which environments may be chosen for this field right now, and what each one
 * would ask of the operator.
 *
 * A READ: it registers nothing, mints no destination and creates no pairing,
 * because merely opening a chooser the user may cancel must not leave state
 * behind. `available` / `needsInPageApproval` / `needsAuthorization` all come
 * from the server's own environmentOptions(), so the popup can never offer a
 * card the server would then refuse, nor promise "automatic" for a card that
 * is about to ask for something.
 *
 * The middle name USED TO BE `needsRemoteApproval`, and it was true for
 * `remote`. Both halves of that were wrong: the in-page approval is raised by
 * the server inside ITS OWN browser, so it belongs to LOCAL, and the word
 * "remote" in the identifier is exactly what made the mistake read as correct
 * for as long as it did.
 */
async function targetingOptions(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error, options: [] };

  var nodeId = String((payload && payload.nodeId) || '').trim();
  var fieldKey = String((payload && payload.fieldKey) || '').trim();
  // ── NO FIELD YET IS THE NORMAL CASE, NOT AN ERROR ─────────────────────
  // This line used to be the whole of what the operator was looking at. It read
  //   `return { ok: false, error: 'no_target_field', options: [] };`
  // and produced, verbatim on screen, the questions:
  //
  //   «این کجاشه فیلد های بخش ریموت؟»
  //   «کجاس فیلد اتورایزشن؟»
  //   «اصلا اینپوت ردیو کجاست که انتخاب کنم ریموت یا لوکالشو؟»
  //
  // The popup asks this question THE MOMENT IT OPENS — before anything has been
  // targeted, because that is what a chooser is FOR. Refusing then meant the
  // popup received zero options, rendered zero cards, and printed the raw token
  // `no_target_field` exactly where the two radios belong. Un-hiding #envCard
  // could not help: there was nothing to put inside it.
  //
  // WHICH BROWSERS EXIST DOES NOT DEPEND ON A FIELD. It is a property of the
  // server (is the local runtime switched on?) and of the fixed catalogue in
  // BrowserEnvironment.ts. So ask the server WITHOUT a field, and fall back to
  // the pair we know it publishes if it cannot be reached at all — an offline
  // popup must still be able to show that a choice exists.
  //
  // `fieldScoped: false` is carried out so nothing downstream can mistake this
  // for an answer about a particular field: `paired` is false and `pairingKey`
  // is empty here BECAUSE THERE IS NO FIELD, not because a field is unpaired.
  if (!nodeId || !fieldKey) {
    var res0 = await apiFetch(ctx.base + '/inspector/targeting/options', { method: 'GET' }, ctx.apiKey);
    var d0 = (res0 && res0.data) || {};
    if (res0 && res0.ok && Array.isArray(d0.options) && d0.options.length) {
      return {
        ok: true,
        fieldScoped: false,
        options: d0.options,
        paired: false,
        localEnabled: !!d0.localEnabled,
        pairingKey: ''
      };
    }
    // Offline fallback, mirroring src/core/BrowserEnvironment.ts. Marked
    // `offline` so a status line can explain why nothing is pre-selected rather
    // than implying the server answered.
    return {
      ok: true,
      fieldScoped: false,
      offline: true,
      options: [
        { id: 'local',  available: true, paired: false, needsAuthorization: false, needsInPageApproval: true,  opensServerBrowser: true,  note: '' },
        { id: 'remote', available: true, paired: false, needsAuthorization: true,  needsInPageApproval: false, opensServerBrowser: false, note: '' }
      ],
      paired: false,
      localEnabled: true,
      pairingKey: ''
    };
  }

  var qs = '?nodeId=' + encodeURIComponent(nodeId) + '&fieldKey=' + encodeURIComponent(fieldKey);
  if (payload && payload.workflowId) qs += '&workflowId=' + encodeURIComponent(payload.workflowId);

  var res = await apiFetch(ctx.base + '/inspector/targeting/options' + qs, { method: 'GET' }, ctx.apiKey);
  var data = (res && res.data) || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'Could not ask the server which browsers are available.',
      options: []
    };
  }
  return {
    ok: true,
    options: data.options || [],
    paired: !!data.paired,
    localEnabled: !!data.localEnabled,
    pairingKey: data.pairingKey || ''
  };
}

/**
 * The operator chose an environment. Hand it to the server and store what comes
 * back.
 *
 * The ENVIRONMENT is the only thing sent. The binding, the address and the
 * credential all come back FROM the server, which is what keeps this surface
 * incapable of asserting a target for itself:
 *
 *   LOCAL   -> `openServerBrowser: true` plus a consent prompt. LOCAL means
 *              local TO THIS PROJECT: the browser on the same machine as the
 *              backend, which is therefore the one thing this server can
 *              actually launch. No Base URL, no API key and no Authorization
 *              Code are asked for, because there is no second machine to carry
 *              them to. What IS asked for is an approval inside that browser,
 *              and not out of distrust: ONE server browser is shared by every
 *              field and outlives any single pick, so it has to be told which
 *              field this one is. True whether or not it was already running:
 *
 *                «اگر بالا باشه که الرت میده، اگر بالا نباشه یکی بالا میاره و بعدش الرت میده»
 *
 *   REMOTE  -> `step: 'authorize'` and an `authorization` payload. REMOTE means
 *              remote FROM THIS PROJECT: the browser on the operator's own
 *              personal machine. Two machines, a real trust gap, so a Base URL
 *              and a fresh per-field code are required — and nothing is
 *              launched, because that browser is already open and this server
 *              cannot reach it.
 *
 * NEITHER branch stores the target here. LOCAL's destination is written by
 * consentDecide() when the human presses Allow; REMOTE's by inspectorPair()
 * when the code is redeemed. Storing it at BEGIN time would bind a field to a
 * browser that never answered — which is the whole reason both settling acts
 * exist. These two descriptions were previously attached to the wrong
 * environments, and that swap was the reported defect:
 *
 *     «وقتی لوکال میزنم باید مرورگر لوکال سرور بالا بیاد ولی برعکسه»
 */
async function targetingBegin(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var environment = (payload && payload.environment) === 'local' ? 'local' : 'remote';
  var nodeId = String((payload && payload.nodeId) || '').trim();
  var fieldKey = String((payload && payload.fieldKey) || '').trim();
  if (!nodeId || !fieldKey) return { ok: false, error: 'no_target_field' };

  var body = {
    nodeId: nodeId,
    fieldKey: fieldKey,
    action: (payload && payload.action) || '',
    environment: environment
  };
  if (payload && payload.workflowId) body.workflowId = payload.workflowId;
  if (payload && payload.label) body.label = payload.label;

  // ── FIELD IDENTITY: the half of the comparison only THIS side knows ────────
  //
  // The server decides MATCH vs MISMATCH by comparing the field the Project is
  // targeting against the field THIS EXTENSION currently holds. It has the first
  // operand; only we have the second, because it lives in this browser's
  // chrome.storage.local under `ab_targetFieldId`.
  //
  // Until this line existed the value was stored, read by the popup, and never
  // once transmitted — so the server had nothing to compare against and could
  // only act unconditionally. That missing wire is why re-opening an
  // already-bound field still raised a prompt (LOCAL) or minted a fresh code
  // (REMOTE): not a policy decision, just an operand that never arrived.
  //
  // Declared BOTH ways on purpose, exactly as `x-browser-environment` is on the
  // consent-polling call: the query string is visible in a server log when
  // diagnosing this class of bug, and the header survives a proxy that rewrites
  // query strings. src/core/FieldIdentity.ts accepts either and treats them
  // identically.
  //
  // An EMPTY value is sent as nothing at all rather than as `''` or the string
  // 'null'. "I hold no field" is a real, common answer — a freshly installed
  // extension — and it must reach the server as absent, which the rule turns
  // into MISMATCH. Sending the literal text 'null' would be a stringification
  // accident that only LOOKED like a mismatch, for the wrong reason.
  // THE STABLE identity, not the address. `ab_targetFieldId` is re-minted on
  // every NDV open (see getPairingKey's doc comment above), so declaring it here
  // would guarantee a MISMATCH forever — the server would compare two
  // freshly-minted random strings and, quite correctly, find them different every
  // time. `ab_pairingKey` is derived from workflow+node+field and is identical on
  // the next open, which is the only reason "the same field" is a question that
  // can be answered at all.
  var heldFieldId = await getPairingKey();
  var beginUrl = ctx.base + '/inspector/targeting/begin';
  var beginHeaders = {};
  if (heldFieldId) {
    beginHeaders['x-extension-field-id'] = heldFieldId;
    beginUrl += '?extensionFieldId=' + encodeURIComponent(heldFieldId);
  }

  var res = await apiFetch(
    beginUrl,
    { method: 'POST', headers: beginHeaders, body: JSON.stringify(body) },
    ctx.apiKey
  );
  var data = (res && res.data) || {};
  if (!res.ok) {
    // `local_disabled` / `local_unavailable` are passed through with the
    // server's own sentence: the operator's switch is the fix, and a generic
    // failure would hide it.
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'The browser environment could not be selected.',
      environment: environment
    };
  }

  var target = data.target || null;

  // NOTHING IS STORED HERE, in either environment, and that is the whole point.
  //
  // A previous revision adopted the returned target immediately for `local`. It
  // cannot: LOCAL is the server's shared browser, and the server answers a LOCAL
  // begin by raising an in-page approval prompt. Storing the destination before
  // that prompt is answered would make the Allow button decorative — the field
  // would already be bound, and a pick could land in a node the operator never
  // confirmed. Approval is what writes it (see AB_CONSENT_DECIDE).
  //
  // REMOTE stores nothing either, for the mirror-image reason: the destination
  // arrives when the Authorization Code is redeemed, not when it is issued.
  //
  // So in both environments the destination is written by the ACT that settles
  // it, never by this call.
  return {
    ok: true,
    environment: environment,
    step: data.step || 'targeting',
    target: target,
    paired: !!data.paired,
    runtime: data.runtime || '',
    // TRUE for LOCAL — the browser this server can actually launch. Named for
    // what it opens; `openRemoteBrowser` said the opposite of what it did.
    openServerBrowser: !!data.openServerBrowser,
    consent: data.consent || null,
    // REMOTE only: the code + Base URL the operator carries to their own
    // browser. Null for LOCAL, where there is nothing to transcribe.
    authorization: data.authorization || null
  };
}

/**
 * Redeem an Authorization Code. THE REMOTE PATH, and the only writer of a
 * REMOTE destination.
 *
 * This is what the operator's own browser does with the code the dashboard
 * showed them. It is the mirror of consentDecide(): both end with a target field
 * in storage, but they answer different questions —
 *
 *   consentDecide  "the server asked me to confirm a field; I approve."  LOCAL
 *   inspectorPair  "I hold a code the server minted; here it is."        REMOTE
 *
 * `baseUrl` is accepted as an argument because in REMOTE the extension may not
 * know the server's address yet — that is exactly the gap the Base URL box
 * fills. It is persisted on success so subsequent calls need no argument.
 */
/**
 * Turn a failed /inspector/pair attempt into a sentence that names the CAUSE.
 *
 * ── WHY THIS EXISTS ───────────────────────────────────────────────────────
 * REPORTED: «با اینکه همه چیزم درسته هم خود Authorize ام و هم Base URL ام
 * درسته خب بازم همون خطا را بهم برمی‌گردونه».
 *
 * `apiFetch` reduces every outcome to a token: 'network' for anything that
 * prevented a response, 'http_<status>' for anything the server refused. Both
 * were rendered by the popup as "That authorization code was not accepted",
 * which is a diagnosis, not a report — and for two of the three cases it is the
 * WRONG diagnosis. An operator told their code is bad will go and get another
 * code. If the real problem is an unreachable address, a proxy in the way, or an
 * https/http mismatch, they can repeat that loop indefinitely without ever
 * touching the thing that is broken.
 *
 * ── THE THREE CASES, KEPT SEPARATE ────────────────────────────────────────
 *   1. NO RESPONSE AT ALL ('network'). Nothing reached a server, so the code was
 *      not even read. The address, the scheme, DNS, a firewall or a server that
 *      is not running are the candidates — and they are the candidates the
 *      operator can actually check. The address is quoted back for exactly the
 *      reason a typo in it is invisible in a one-line input.
 *   2. THE SERVER ANSWERED, WITH A STATUS. It exists and is reachable; that is
 *      real progress and worth saying. 404 in particular means the address is
 *      live but is not this application (a wrong port, or a proxy fronting
 *      something else) — the single most common misconfiguration here, and
 *      indistinguishable from a bad code in the old message.
 *   3. THE SERVER REFUSED THE CODE, with a reason of its own. Only here is the
 *      code the subject, and only here is the server's own wording used.
 *
 * Preferring `data.error` whenever the server sent one is deliberate: the server
 * knows things this worker cannot (expired vs unknown vs already-redeemed), and
 * overwriting its sentence with a guess would be the same mistake in reverse.
 */
function explainPairFailure(res, data, base) {
  // Case 3 first: if the server said something, the server wins.
  if (data && data.error) return String(data.error);

  var status = (res && res.status) || 0;

  // Case 1 — nothing came back.
  if (!status || (res && res.error === 'network')) {
    var why = (res && res.message) ? ' (' + res.message + ')' : '';
    return 'Could not reach ' + base + why + '. The authorization code was never sent, '
      + 'so it is still valid. Check that the Base URL is exactly the address the '
      + 'dashboard showed, that it includes https:// if the server uses it, and that '
      + 'this machine can open it in a tab.';
  }

  // Case 2 — a real HTTP answer, with the two statuses worth naming.
  if (status === 404) {
    return base + ' answered, but it has no /inspector/pair endpoint (HTTP 404). '
      + 'That address is reachable but is not this application \u2014 check the port, '
      + 'and any proxy in front of it.';
  }
  if (status === 429) {
    return base + ' is rate-limiting pairing attempts (HTTP 429). Wait a moment, '
      + 'then press Connect again with the same code.';
  }
  if (status >= 500) {
    return base + ' returned a server error (HTTP ' + status + '). The address is '
      + 'right; the server could not complete the pairing. Check the server log.';
  }
  if (status === 403 || status === 401) {
    return 'The server refused this authorization code (HTTP ' + status + '). '
      + 'Codes are single-use and short-lived \u2014 mint a fresh one from '
      + 'Target This Field \u2192 Remote Browser.';
  }
  return base + ' refused the request (HTTP ' + status + ').';
}

async function inspectorPair(payload) {
  var typedBase = normalizeBase((payload && payload.baseUrl) || '');
  // Normalized exactly as the server will read it: the dashboard DISPLAYS
  // `ABCD-EFGH`, and `redeem()` strips every non-alphanumeric before comparing.
  // Sending the dash would have been fine, but normalizing here means the string
  // shown in the popup is the string that gets compared — so a code cannot fail
  // for a formatting reason the operator can see and cannot explain.
  var code = String((payload && payload.code) || '')
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, '')
    .slice(0, 16);
  if (!code) return { ok: false, error: 'Enter the authorization code from the dashboard.' };

  var ctx = await inspectorContext();

  // ── WHY THE MANUFACTURED LOOPBACK GUESS IS REFUSED ON THIS PATH ───────────
  //
  // REPORTED: «هم خود Authorize ام و هم Base URL ام درسته خب بازم همون خطا را
  // بهم برمی‌گردونه خب یعنی وصل نمیشه.»
  //
  // This line used to read:
  //
  //     var base = typedBase || (ctx.error ? '' : ctx.base);
  //
  // and `ctx.base` is never empty — inspectorContext() guarantees an address by
  // falling back to `http://127.0.0.1:<port>` (see step 3 of its resolution
  // order). That fallback is CORRECT for every other call in this file, because
  // every other call is made by an extension the server itself seeded, where
  // loopback really is the backend. It is WRONG here and only here, for a reason
  // that is structural rather than incidental:
  //
  //     inspectorPair() is the REMOTE path. Its entire premise is that the
  //     server is on a DIFFERENT machine. Loopback on this machine is therefore
  //     the one address that is guaranteed not to be the server.
  //
  // So an empty Base URL box did not produce "tell me the address". It produced
  // a POST to a port on the operator's own laptop, a connection refusal, and —
  // because apiFetch collapses every transport failure to the token 'network' —
  // a popup message blaming the authorization code. The operator re-copied a
  // perfectly good code as many times as they liked; the request was never
  // leaving their machine.
  //
  // ── WHAT IS REJECTED IS THE *GUESS*, NOT EVERY RESOLVED ADDRESS ───────────
  //
  // The first cut of this fix used `var base = typedBase;` — the typed box as
  // the only source. That killed the bug but it also broke a true case, and the
  // seam suite said so immediately: an extension the SERVER SEEDED carries a
  // real, configured address (from `AB_BOOTSTRAP`, or stored from a pair that
  // already worked) and may legitimately redeem a code without anyone retyping
  // it. Refusing that would demand the operator hand-type an address the
  // extension was literally installed with.
  //
  // inspectorContext() already draws exactly the line that matters, and it
  // reports it in `baseUrlSource`:
  //
  //   'bootstrap' / stored → SOMEONE CONFIGURED THIS. Trustworthy: it came from
  //                          the server that seeded the copy, or from an address
  //                          that previously completed a pair.
  //   'server-local'       → NOBODY CONFIGURED ANYTHING. `http://127.0.0.1:<port>`
  //                          is manufactured by step 3 as a last resort.
  //
  // Only the manufactured one is refused here, and only on THIS path, because
  // this path is REMOTE: its entire premise is that the server is on a DIFFERENT
  // machine, so loopback on this machine is the one address guaranteed not to be
  // it. Every other call in this file is made by a server-seeded extension where
  // loopback genuinely IS the backend, which is why the guess stays correct
  // everywhere else and must not be removed globally.
  var guessedOnly = !ctx.error && ctx.baseUrlSource === 'server-local';
  var base = typedBase || (ctx.error || guessedOnly ? '' : ctx.base);
  if (!base) {
    return {
      ok: false,
      reason: 'no_base_url',
      error: 'Enter the Base URL of your server \u2014 the address this browser can reach it at.'
    };
  }

  var res = await apiFetch(
    base + '/inspector/pair',
    { method: 'POST', body: JSON.stringify({ code: code }) },
    ctx.apiKey
  );
  var data = (res && res.data) || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      // ── SAY WHICH THING FAILED ──────────────────────────────────────
      // The second half of the reported bug. Every failure here used to arrive
      // as "That authorization code was not accepted", including the failures
      // that never reached a server and therefore never saw the code at all.
      // That message sent the operator to fix the one input that was right.
      //
      // explainPairFailure() separates the three real cases — unreachable
      // address, an HTTP status from a server that DID answer, and an actual
      // refusal of the code — and names the address it tried, because a typo in
      // the host is invisible in a short input box.
      error: explainPairFailure(res, data, base)
    };
  }

  // Persist the address that worked, so the next field needs only a code.
  if (typedBase) await new Promise(function (r) {
    chrome.storage.local.set({ ab_baseUrl: typedBase }, function () { r(); });
  });

  // ── STORE THE CLIENT TOKEN. THE STEP THAT MAKES REMOTE WORK AT ALL ────────
  //
  // Returned only when this extension had no credential of its own, which is
  // the hand-installed REMOTE case — and this is the ONLY moment it exists. The
  // server keeps a lookup entry, not a way to re-derive it, so an extension that
  // drops it here must redeem another code to get back in.
  //
  // Filed as `ab_apiKey` deliberately, rather than as a new key of its own.
  // `apiFetch` already attaches that value as `x-api-key` on every call, and
  // `inspectorContext()` already resolves it — so one write makes the token flow
  // through submits, consent polls and status checks with no other change. The
  // server accepts it on exactly those paths (see the inspector auth middleware
  // in src/index.ts) and nowhere else, so widening the storage key does not
  // widen what the token can do.
  //
  // Written BEFORE the target field id, because a stored destination that no
  // request can authenticate against is the worse of the two half-states.
  if (data.clientToken) {
    await new Promise(function (r) {
      chrome.storage.local.set({
        ab_apiKey: data.clientToken,
        // Recorded so the popup can tell the operator WHY it is connected
        // without a key they ever typed, and so a future 'unpair' knows there is
        // a server-side token to revoke rather than a key to leave alone.
        ab_credentialKind: 'client_token'
      }, function () { r(); });
    });
  }

  if (data.targetFieldId) {
    await setTargetFieldId(data.targetFieldId);
    await setTargetEnvironment('remote');
  }

  return { ok: true, paired: true, environment: 'remote', targetFieldId: data.targetFieldId || '' };
}

/** Read the current browser mode (Remote / Local) for the popup's indicator. */
async function getBrowserMode() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  return apiFetch(ctx.base + '/browser-mode', { method: 'GET' }, ctx.apiKey);
}

/** Switch mode from the extension. 409 means the backend refused, with a note. */
async function setBrowserMode(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var mode = payload && payload.mode;
  if (!mode) return { ok: false, error: 'no_mode' };

  var res = await apiFetch(
    ctx.base + '/browser-mode',
    { method: 'POST', body: JSON.stringify({ mode: mode }) },
    ctx.apiKey
  );
  var data = res.data || {};
  if (!res.ok) {
    return { ok: false, reason: data.note || res.error, error: data.error || 'Could not switch mode.', data: data };
  }
  return { ok: true, data: data };
}

// ════════════════════════════════════════════════════════════════
// Remote -> Local handoff
//
// Thin wrappers over lib/ab-handoff.js. The base URL is resolved from settings
// here rather than passed in from the popup, so the extension can only ever pair
// with the backend it is configured for -- a code typed into the wrong window
// cannot redirect it somewhere else.
//
// NOTE these deliberately do NOT require an API key, unlike every other call in
// this worker. The whole point of the pairing code is that the extension joins a
// session WITHOUT holding the key that controls the entire instance, so demanding
// one here would defeat the security model and also break the realistic case:
// a user installing the extension for the first time has a code but no key.
// ════════════════════════════════════════════════════════════════

function handoffAvailable() {
  return (typeof ABHandoff !== 'undefined') && ABHandoff;
}

// Resolved through the same internal path as everything else, so this cannot
// ask for a Base URL the popup no longer collects.
async function handoffBase() {
  var ctx = await inspectorContext();
  return (ctx && ctx.base) || '';
}

async function handoffPair(payload) {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  if (!base) {
    // Was 'Set the backend Base URL in this popup first, then enter the code.'
    // There is no such box any more, and the address is the server's to state.
    return {
      ok: false,
      reason: 'runtime_context_unavailable',
      error: 'This browser has not been given a backend address by the server yet.'
    };
  }
  var res = await ABHandoff.pairWithCode(base, payload && payload.code);
  return res;
}

async function handoffApply() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  return ABHandoff.applyHandoff({ baseUrl: base });
}

async function handoffStatus() {
  if (!handoffAvailable()) return { ok: false, paired: false, error: 'Handoff module failed to load.' };
  var s = await ABHandoff.status();
  return Object.assign({ ok: true }, s);
}

async function handoffUnpair() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  await ABHandoff.clearPairing();
  return { ok: true };
}

/**
 * Toggle the picker in the active tab.
 *
 * The content script is asked first; if it is not there (a tab opened before
 * the extension was installed, or reloaded) it is injected on the spot, so the
 * user is never told to reload the page.
 */
async function toggleInspector(desired) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }

      var type = desired === 'stop' ? 'ab-inspector-stop' : 'ab-inspector-start';
      chrome.tabs.sendMessage(tab.id, { type: type }, function (resp) {
        if (!chrome.runtime.lastError) { resolve(resp || { ok: true }); return; }
        if (!chrome.scripting || !chrome.scripting.executeScript) {
          resolve({ ok: false, error: 'no_content_script' });
          return;
        }
        // Same file order as the manifest: extraction core and selectors must
        // exist before inspector.js runs.
        chrome.scripting.executeScript({
          target: { tabId: tab.id },
          files: ['lib/ab-inspect.js', 'content/selector.js', 'content/inspector.js']
        }, function () {
          if (chrome.runtime.lastError) {
            resolve({ ok: false, error: 'inject_failed', message: chrome.runtime.lastError.message });
            return;
          }
          chrome.tabs.sendMessage(tab.id, { type: type }, function (resp2) {
            if (chrome.runtime.lastError) { resolve({ ok: false, error: 'no_content_script' }); return; }
            resolve(resp2 || { ok: true });
          });
        });
      });
    });
  });
}

// The keyboard shortcut works with no popup open. Note that Chrome may decline
// to register Ctrl+Shift+C because DevTools claims it; inspector.js also listens
// for the chord in-page, so the gesture works either way.
if (chrome.commands && chrome.commands.onCommand) {
  chrome.commands.onCommand.addListener(function (command) {
    if (command === 'toggle-inspector') toggleInspector('toggle');
  });
}

// Relay a control message to the active tab's content script.
async function relayToActiveTab(message) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }
      chrome.tabs.sendMessage(tab.id, message, function (resp) {
        if (chrome.runtime.lastError) {
          resolve({ ok: false, error: 'no_content_script' });
        } else {
          resolve(resp || { ok: true });
        }
      });
    });
  });
}

chrome.runtime.onMessage.addListener(function (msg, sender, sendResponse) {
  if (!msg || !msg.type) return;
  switch (msg.type) {
    case 'AB_SEND_FLOW':
      sendFlow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_CHECK':
      checkConnection().then(sendResponse);
      return true; // async
    case 'AB_LIST_WORKFLOWS':
      listWorkflows().then(sendResponse);
      return true; // async
    case 'AB_RUN_SAVED':
      runSavedWorkflow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_START':
      startLive(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_STOP':
      sendResponse(stopLive(msg.payload));
      return false;
    case 'AB_OPEN_PANEL':
      openPanel().then(sendResponse);
      return true; // async
    case 'AB_RELAY':
      relayToActiveTab(msg.message).then(sendResponse);
      return true; // async

    // ---- Element Inspector -------------------------------------------------
    // Sent by content/inspector.js when the user presses "Confirm & Add to Node".
    case 'ab-inspector-submit':
      submitElement(msg).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_SESSION':
      inspectorSession().then(sendResponse);
      return true; // async
    // AB_INSPECTOR_PAIR IS routed — see the case further down. The comment that
    // used to sit here said the opposite ("deliberately NO 'AB_INSPECTOR_PAIR'
    // case here any more") while the case was fifteen lines below it, and also
    // had the environments backwards. Corrected rather than deleted, because the
    // distinction it was reaching for is real:
    //
    //   inspectorPair()  REMOTE only. Redeems an authorization code against
    //                    POST /inspector/pair. REMOTE is the operator's own
    //                    machine, so a credential is the only thing that can
    //                    prove which field they are allowed to bind.
    //   consentDecide()  LOCAL only. No code exists in LOCAL; the operator
    //                    approves a prompt instead (AB_CONSENT_DECIDE below).
    //
    // Either way the server acts only on MISMATCH: an extension already holding
    // the field the project is targeting is prompted for nothing and issued
    // nothing.
    //
    // Note AB_HANDOFF_PAIR further down is a DIFFERENT subsystem — it binds a
    // BROWSER SESSION, not a target field — and is intentionally untouched.
    // ---- Browser Environment: the LOCAL / REMOTE choice ------------------
    // The FIRST step of targeting, offered here as well as in the dashboard,
    // because this popup is the surface reached from inside the browser being
    // targeted. Both cases delegate to the routes the dashboard chooser already
    // uses; neither adds a binding rule of its own.
    case 'AB_TARGETING_OPTIONS':
      targetingOptions(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_TARGETING_BEGIN':
      targetingBegin(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_PAIR':
      inspectorPair(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_UNPAIR':
      inspectorUnpair().then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_TOGGLE':
      toggleInspector(msg.desired).then(sendResponse);
      return true; // async

    // ---- Remote targeting consent -----------------------------------------
    // How a REMOTE browser acquires its target: by answering a question the
    // server delivered, never by transcribing a code. (A LOCAL browser needs
    // nothing at all — the server binds the field when the crosshair is used.)
    // Which browser am I? Asked by content/consent.js before it starts polling,
    // so a local browser never runs the approval loop at all, and by the popup
    // so it can state the environment instead of leaving the operator guessing.
    case 'AB_ENVIRONMENT':
      browserEnvironment().then(function (env) {
        sendResponse({ ok: true, environment: env });
      });
      return true; // async
    case 'AB_CONSENT_LIST':
      // `sender` carries the calling tab; consentList() uses it to decide
      // whether THIS tab is the one that may show the Alert.
      consentList(sender).then(sendResponse);
      return true; // async
    case 'AB_CONSENT_DECIDE':
      consentDecide(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_MODE_GET':
      getBrowserMode().then(sendResponse);
      return true; // async
    case 'AB_MODE_SET':
      setBrowserMode(msg.payload).then(sendResponse);
      return true; // async

    // ---- Remote <-> Local handoff -----------------------------------------
    case 'AB_HANDOFF_PAIR':
      handoffPair(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_APPLY':
      handoffApply().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_STATUS':
      handoffStatus().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_UNPAIR':
      handoffUnpair().then(sendResponse);
      return true; // async
    default:
      return false;
  }
});
