/* ============================================================
   background.js — service worker (Step 13, extended in Step 31).
   - Performs the secure POST /run to the backend. Doing the fetch
     here (extension-privileged, with host_permissions) avoids the
     page-context CORS restrictions a content script would hit.
   - Step 31: makes the extension a thin client of the SAME backend the
     dashboard panel uses (Model A): it can list saved workflows
     (GET /workflows/:userId), run a saved workflow
     (POST /workflows/:userId/:workflowId/run), open the panel tab, and
     stream a job's live events over SSE — forwarding each event to the
     popup so it can paint per-node tick/error (mirroring Step 26).
   - Relays a few control messages from the popup to the active tab's
     content script (picker/recorder toggles).

   Settings (backend base URL, API key, userId) live in
   chrome.storage.local: ab_baseUrl, ab_apiKey, ab_userId.
   API key is never logged.

   Pure URL/parse/event logic is shared with the popup (and unit tests)
   via lib/ab-core.js — imported here as the global ABCore.
   ============================================================ */
'use strict';

// Service workers can pull in classic scripts synchronously. ab-core.js is a
// pure, DOM-free module that also runs in the popup and in vitest (one source
// of truth for URL building, list parsing and live-event mapping).
try { importScripts('lib/ab-core.js'); } catch (e) { /* ABCore optional fallback below */ }

// ab-handoff.js is the Local half of the Remote <-> Local switch. It lives HERE
// rather than in the popup on purpose: restoring a session opens N tabs and then
// reports completion, and the popup is destroyed the instant the user clicks
// away or Chrome moves focus to a new tab. A restore hosted in the popup would
// be killed mid-sequence, leaving some tabs open, nothing focused and the server
// still waiting -- exactly the "half-moved browser" state the ordering inside
// applyHandoff() is designed to avoid. The worker outlives the popup, so the
// popup only sends a message and the sequence completes regardless.
try { importScripts('lib/ab-handoff.js'); } catch (e) { /* ABHandoff optional; guarded at use */ }

// Optional, and present ONLY in the copy the server side-loads into the REMOTE
// browser (generated by src/core/InspectorExtension.ts). It is absent from the
// authored `extension/` directory and from any hand-installed copy, so the
// failure to import is the normal case for a user's own Chrome — hence a plain
// swallow rather than a warning.
try { importScripts('bootstrap.config.js'); } catch (e) { /* not a managed copy */ }

/**
 * Apply the server's bootstrap settings as DEFAULTS.
 *
 * WHY THIS EXISTS
 * ---------------
 * When the server side-loads this extension into the remote browser, the fresh
 * profile has an EMPTY `chrome.storage.local`. Without this, the popup would open
 * inside a remote desktop asking the user for the address and API token of the
 * very server that just launched the browser they are looking at — something
 * they cannot read from in there, and should not have to.
 *
 * WHY IT CAN ONLY EVER FILL IN BLANKS
 * -----------------------------------
 * Each key is written only when it is currently empty. A user who typed their own
 * base URL or key keeps it, on this launch and on every launch after — a managed
 * default that silently reverted a deliberate setting would be far worse than no
 * default at all. That is also why it is not `chrome.storage.local.set(all)`.
 */
async function applyBootstrapDefaults() {
  if (typeof AB_BOOTSTRAP === 'undefined' || !AB_BOOTSTRAP) return;
  var current = await new Promise(function (resolve) {
    chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
      resolve(s || {});
    });
  });

  var patch = {};
  if (!current.ab_baseUrl && AB_BOOTSTRAP.baseUrl) patch.ab_baseUrl = AB_BOOTSTRAP.baseUrl;
  if (!current.ab_apiKey && AB_BOOTSTRAP.apiKey) patch.ab_apiKey = AB_BOOTSTRAP.apiKey;
  if (!current.ab_userId && AB_BOOTSTRAP.userId) patch.ab_userId = AB_BOOTSTRAP.userId;
  if (!Object.keys(patch).length) return;

  await new Promise(function (resolve) {
    chrome.storage.local.set(patch, function () { resolve(); });
  });
}

// On install AND on every worker start: an MV3 service worker is killed when
// idle, and `onInstalled` does not fire again when it is revived. Running it on
// load as well is what makes the settings reliably present.
if (chrome.runtime && chrome.runtime.onInstalled) {
  chrome.runtime.onInstalled.addListener(function () {
    applyBootstrapDefaults().catch(function () { /* defaults are best-effort */ });
  });
}
var abBootstrapReady = applyBootstrapDefaults().catch(function () { /* best-effort */ });

function getSettings() {
  // Await the bootstrap before reading, so the FIRST request out of a freshly
  // seeded extension is already configured instead of failing with
  // `no_base_url` and needing a retry the user has to guess at.
  return abBootstrapReady.then(function () {
    return new Promise(function (resolve) {
      chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
        resolve({
          baseUrl: (s && s.ab_baseUrl) || '',
          apiKey: (s && s.ab_apiKey) || '',
          userId: (s && s.ab_userId) || 'local'
        });
      });
    });
  });
}

// Prefer the shared ABCore.normalizeBase; keep a tiny local fallback so the
// worker still functions if importScripts ever fails.
function normalizeBase(url) {
  if (typeof ABCore !== 'undefined' && ABCore.normalizeBase) return ABCore.normalizeBase(url);
  var u = String(url || '').trim();
  if (!u) return '';
  if (!/^https?:\/\//i.test(u)) u = 'http://' + u;
  return u.replace(/\/+$/, '');
}

// Small JSON fetch helper that always returns { ok, status, data, error? }.
async function apiFetch(url, opts, apiKey) {
  var headers = Object.assign(
    { 'Content-Type': 'application/json' },
    apiKey ? { 'x-api-key': apiKey } : {},
    (opts && opts.headers) || {}
  );
  try {
    var res = await fetch(url, Object.assign({}, opts, { headers: headers }));
    var text = await res.text();
    var data;
    try { data = text ? JSON.parse(text) : null; } catch (e) { data = { raw: text }; }
    if (!res.ok) return { ok: false, error: 'http_' + res.status, status: res.status, data: data };
    return { ok: true, status: res.status, data: data };
  } catch (e) {
    return { ok: false, error: 'network', message: String((e && e.message) || e) };
  }
}

// Send the recorded steps to the backend as an inline Flow (POST /run).
async function sendFlow(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };

  var steps = Array.isArray(payload && payload.steps) ? payload.steps : [];
  if (!steps.length) return { ok: false, error: 'no_steps' };

  var body = { userId: cfg.userId || 'local', steps: steps, headless: true };
  if (payload && payload.webhookUrl) body.webhookUrl = payload.webhookUrl;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunInlineUrl)
    ? ABCore.buildRunInlineUrl(base, { wait: !!(payload && payload.wait) })
    : base + '/run';
  return apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, cfg.apiKey);
}

// Validate the API key / connectivity via GET /me. Returns data so the popup
// can resolve the canonical userId the key is bound to.
async function checkConnection() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  return apiFetch(base + '/me', { method: 'GET' }, cfg.apiKey);
}

// Step 31: list the user's saved workflows — the SAME list the panel shows.
async function listWorkflows() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var userId = cfg.userId || 'local';
  var res = await apiFetch(base + '/workflows/' + encodeURIComponent(userId), { method: 'GET' }, cfg.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.parseWorkflowList) {
    res.workflows = ABCore.parseWorkflowList(res.data);
  }
  return res;
}

// Step 31: run a saved, versioned workflow (Model B contract, shared with the
// n8n node) and return the jobId so the popup can subscribe to live events.
async function runSavedWorkflow(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var workflowId = payload && payload.workflowId;
  if (!workflowId) return { ok: false, error: 'no_workflow_id' };

  var userId = cfg.userId || 'local';
  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunSavedUrl)
    ? ABCore.buildRunSavedUrl(base, userId, workflowId, { wait: !!(payload && payload.wait) })
    : base + '/workflows/' + encodeURIComponent(userId) + '/' + encodeURIComponent(workflowId) + '/run';

  var body = {};
  if (payload && payload.triggerData) body.triggerData = payload.triggerData;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var res = await apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, cfg.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.extractJobId) {
    res.jobId = ABCore.extractJobId(res.data);
  }
  return res;
}

// ---- Live (SSE) streaming -------------------------------------------------
// We stream a job's events here in the worker (host-privileged) and forward
// each mapped status delta to the popup via runtime messages, so the popup can
// paint tick/error per node even though EventSource cannot set headers.
var liveControllers = {}; // jobId -> AbortController

function broadcast(message) {
  try { chrome.runtime.sendMessage(message, function () { void chrome.runtime.lastError; }); } catch (e) { /* popup closed */ }
}

async function startLive(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var jobId = payload && payload.jobId;
  if (!jobId) return { ok: false, error: 'no_job_id' };
  var userId = (payload && payload.userId) || cfg.userId || 'local';

  // stop a previous stream for the same job if any
  if (liveControllers[jobId]) { try { liveControllers[jobId].abort(); } catch (e) { /* noop */ } }
  var controller = new AbortController();
  liveControllers[jobId] = controller;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildSseUrl)
    ? ABCore.buildSseUrl(base, userId, jobId, cfg.apiKey)
    : base + '/live/sse/' + encodeURIComponent(userId) + '/' + encodeURIComponent(jobId) + '?api_key=' + encodeURIComponent(cfg.apiKey);

  // Drive the SSE stream with fetch + ReadableStream (works in MV3 workers,
  // unlike EventSource which is unavailable there).
  (async function pump() {
    try {
      var res = await fetch(url, { method: 'GET', signal: controller.signal });
      if (!res.ok || !res.body) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'http_' + res.status });
        cleanupLive(jobId);
        return;
      }
      var reader = res.body.getReader();
      var decoder = new TextDecoder();
      var buf = '';
      while (true) {
        var chunk = await reader.read();
        if (chunk.done) break;
        buf += decoder.decode(chunk.value, { stream: true });
        var idx;
        // SSE frames are separated by a blank line.
        while ((idx = buf.indexOf('\n\n')) !== -1) {
          var frame = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          handleSseFrame(jobId, frame);
        }
      }
      broadcast({ type: 'AB_LIVE_END', jobId: jobId });
    } catch (e) {
      if (!controller.signal.aborted) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'network', message: String((e && e.message) || e) });
      }
    } finally {
      cleanupLive(jobId);
    }
  })();

  return { ok: true, jobId: jobId };
}

function handleSseFrame(jobId, frame) {
  // Parse the "event:" and "data:" lines of one SSE frame.
  var lines = frame.split('\n');
  var dataLines = [];
  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (line.indexOf('data:') === 0) dataLines.push(line.slice(5).trimStart());
  }
  if (!dataLines.length) return;
  var raw = dataLines.join('\n');
  var ev;
  try { ev = JSON.parse(raw); } catch (e) { return; }

  var status = (typeof ABCore !== 'undefined' && ABCore.mapLiveEventToStatus)
    ? ABCore.mapLiveEventToStatus(ev) : null;
  broadcast({ type: 'AB_LIVE_EVENT', jobId: jobId, event: ev, status: status });

  if (typeof ABCore !== 'undefined' && ABCore.isTerminalEvent && ABCore.isTerminalEvent(ev)) {
    var ctrl = liveControllers[jobId];
    if (ctrl) { try { ctrl.abort(); } catch (e) { /* noop */ } }
  }
}

function cleanupLive(jobId) {
  if (liveControllers[jobId]) { delete liveControllers[jobId]; }
}

function stopLive(payload) {
  var jobId = payload && payload.jobId;
  if (jobId && liveControllers[jobId]) {
    try { liveControllers[jobId].abort(); } catch (e) { /* noop */ }
    cleanupLive(jobId);
  }
  return { ok: true };
}

// Step 31: open (or focus) the dashboard panel — the SAME UI the extension is
// a thin client of.
async function openPanel() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  var url = (typeof ABCore !== 'undefined' && ABCore.buildPanelUrl) ? ABCore.buildPanelUrl(base) : base + '/';
  return new Promise(function (resolve) {
    chrome.tabs.create({ url: url }, function (tab) {
      if (chrome.runtime.lastError) { resolve({ ok: false, error: 'open_failed' }); return; }
      resolve({ ok: true, tabId: tab && tab.id });
    });
  });
}

/* ============================================================
   ELEMENT INSPECTOR

   The content script cannot POST the pick itself: a fetch from page context is
   subject to the page's CSP and to CORS against the backend origin. The worker
   holds host_permissions, so the request belongs here — same reason sendFlow
   lives here.

   The session id is minted here too, and persisted. It identifies WHICH
   automation session this extension is attached to, so the backend can refuse a
   pick aimed at a node that a different session claimed rather than deliver it
   to the wrong place.
   ============================================================ */

// One id per extension installation, stable across popup opens and worker
// restarts (MV3 workers are killed aggressively; an in-memory id would change
// mid-session and every pick would then look like it came from a stranger).
async function getSessionId() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_sessionId'], function (s) {
      var id = s && s.ab_sessionId;
      if (id) { resolve(id); return; }
      var fresh = 'ext-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
      chrome.storage.local.set({ ab_sessionId: fresh }, function () { resolve(fresh); });
    });
  });
}

// Resolve base + key once for the inspector calls, with the same explicit
// error keys the popup already knows how to render.
async function inspectorContext() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { error: 'no_base_url' };
  if (!cfg.apiKey) return { error: 'no_api_key' };
  return { base: base, apiKey: cfg.apiKey, userId: cfg.userId || 'local' };
}

/**
 * What is this extension attached to — which mode, which node is waiting?
 * Asked when the popup opens, so the user can see the answer before picking
 * rather than discovering it from a failed submit.
 *
 * `sessionId` in the answer is the EDITING session that actually holds the
 * claim (`data.activeNode.sessionId`), not this installation's own id — see
 * `claimedSessionId` below for why that distinction was a shipped bug.
 */
async function inspectorSession() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var res = await apiFetch(ctx.base + '/inspector/session', { method: 'GET' }, ctx.apiKey);
  var active = (res && res.data && res.data.activeNode) || null;
  res.sessionId = (active && active.sessionId) || '';
  // Kept separate and clearly named: it identifies the INSTALLATION, which is
  // useful in a log, and is deliberately never sent as the claim's session.
  res.installId = await getSessionId();
  return res;
}

/**
 * The session id to submit a pick under: the one the PROJECT says is editing.
 *
 * THE BUG THIS FIXES
 * ------------------
 * This worker used to submit `getSessionId()` — an id minted HERE, in the
 * extension, of the form `ext-…`. The dashboard claims a node under a per-TAB
 * id of the form `ui-…` (public/js/inspector-client.js), and InspectorHub
 * compares the two for equality:
 *
 *     if (!sessionId || sessionId !== session.sessionId) -> 'stale_session'
 *
 * Two independently generated ids can never be equal, so EVERY pick was
 * refused with `stale_session`. Measured against the real class:
 * claim('ui-abc123') then submit('ext-zzz999') -> {ok:false,'stale_session'}.
 * The whole «Confirm & Add to Node» path was therefore dead, and no test caught
 * it because each side was only ever tested with ids it had chosen itself.
 *
 * WHY READING IT BACK IS STILL SAFE
 * ---------------------------------
 * The guard's purpose is to stop a pick landing in a node the user is no longer
 * editing. That protection lives in the CLAIM, not in who authored the string:
 * the server hands out the session of the node that is open RIGHT NOW, and a
 * submission is refused when no node is open (`no_active_node`). Fetching the
 * value immediately before submitting also means a claim that moved between
 * arming the picker and confirming is honoured, not overridden.
 */
async function claimedSessionId(ctx) {
  var res = await apiFetch(ctx.base + '/inspector/session', { method: 'GET' }, ctx.apiKey);
  if (!res.ok) return { error: res.error || 'unreachable', message: res.message || '' };
  var active = (res.data && res.data.activeNode) || null;
  if (!active || !active.sessionId) return { error: 'no_active_node' };
  return { sessionId: active.sessionId, activeNode: active };
}

/**
 * Deliver a confirmed pick. Returns a flat, popup/panel-friendly shape:
 * on refusal the backend's reason key and sentence are passed through
 * UNCHANGED, because "no node is waiting" is a fixable problem and a generic
 * failure message hides the fix.
 */
async function submitElement(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var element = payload && payload.element;
  var selected = (payload && payload.selected) || [];
  if (!element) return { ok: false, error: 'no_element' };
  if (!selected.length) return { ok: false, error: 'empty_selection' };

  // The session comes from the project, not from here. Refuse locally when no
  // node is open rather than sending a request whose only possible answer is a
  // 409 — the message the user needs is the same either way, and this one
  // arrives without a round trip.
  var claim = await claimedSessionId(ctx);
  if (claim.error) {
    return {
      ok: false,
      reason: claim.error,
      error: claim.error === 'no_active_node'
        ? 'No node is waiting. Open a node in the project, then confirm again.'
        : 'Could not reach the project (' + claim.error + ').'
    };
  }

  var res = await apiFetch(
    ctx.base + '/inspector/element',
    {
      method: 'POST',
      body: JSON.stringify({
        sessionId: claim.sessionId,
        element: element,
        selected: selected
      })
    },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'The element could not be delivered.',
      activeNode: data.activeNode || null
    };
  }

  var node = data.activeNode || {};
  // A confirmation that NAMES the destination ("Click #buy") is what proves the
  // pick did not silently go somewhere else.
  var where = node.label || [node.action, node.nodeId].filter(Boolean).join(' ') || '';
  return { ok: true, node: where, delivery: data.delivery || null, activeNode: node };
}

/** Read the current browser mode (Remote / Local) for the popup's indicator. */
async function getBrowserMode() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  return apiFetch(ctx.base + '/browser-mode', { method: 'GET' }, ctx.apiKey);
}

/** Switch mode from the extension. 409 means the backend refused, with a note. */
async function setBrowserMode(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var mode = payload && payload.mode;
  if (!mode) return { ok: false, error: 'no_mode' };

  var res = await apiFetch(
    ctx.base + '/browser-mode',
    { method: 'POST', body: JSON.stringify({ mode: mode }) },
    ctx.apiKey
  );
  var data = res.data || {};
  if (!res.ok) {
    return { ok: false, reason: data.note || res.error, error: data.error || 'Could not switch mode.', data: data };
  }
  return { ok: true, data: data };
}

// ════════════════════════════════════════════════════════════════
// Remote -> Local handoff
//
// Thin wrappers over lib/ab-handoff.js. The base URL is resolved from settings
// here rather than passed in from the popup, so the extension can only ever pair
// with the backend it is configured for -- a code typed into the wrong window
// cannot redirect it somewhere else.
//
// NOTE these deliberately do NOT require an API key, unlike every other call in
// this worker. The whole point of the pairing code is that the extension joins a
// session WITHOUT holding the key that controls the entire instance, so demanding
// one here would defeat the security model and also break the realistic case:
// a user installing the extension for the first time has a code but no key.
// ════════════════════════════════════════════════════════════════

function handoffAvailable() {
  return (typeof ABHandoff !== 'undefined') && ABHandoff;
}

async function handoffBase() {
  var cfg = await getSettings();
  return normalizeBase(cfg.baseUrl);
}

async function handoffPair(payload) {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  if (!base) {
    return {
      ok: false,
      reason: 'no_base_url',
      error: 'Set the backend Base URL in this popup first, then enter the code.'
    };
  }
  var res = await ABHandoff.pairWithCode(base, payload && payload.code);
  return res;
}

async function handoffApply() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  return ABHandoff.applyHandoff({ baseUrl: base });
}

async function handoffStatus() {
  if (!handoffAvailable()) return { ok: false, paired: false, error: 'Handoff module failed to load.' };
  var s = await ABHandoff.status();
  return Object.assign({ ok: true }, s);
}

async function handoffUnpair() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  await ABHandoff.clearPairing();
  return { ok: true };
}

/**
 * Toggle the picker in the active tab.
 *
 * The content script is asked first; if it is not there (a tab opened before
 * the extension was installed, or reloaded) it is injected on the spot, so the
 * user is never told to reload the page.
 */
async function toggleInspector(desired) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }

      var type = desired === 'stop' ? 'ab-inspector-stop' : 'ab-inspector-start';
      chrome.tabs.sendMessage(tab.id, { type: type }, function (resp) {
        if (!chrome.runtime.lastError) { resolve(resp || { ok: true }); return; }
        if (!chrome.scripting || !chrome.scripting.executeScript) {
          resolve({ ok: false, error: 'no_content_script' });
          return;
        }
        // Same file order as the manifest: extraction core and selectors must
        // exist before inspector.js runs.
        chrome.scripting.executeScript({
          target: { tabId: tab.id },
          files: ['lib/ab-inspect.js', 'content/selector.js', 'content/inspector.js']
        }, function () {
          if (chrome.runtime.lastError) {
            resolve({ ok: false, error: 'inject_failed', message: chrome.runtime.lastError.message });
            return;
          }
          chrome.tabs.sendMessage(tab.id, { type: type }, function (resp2) {
            if (chrome.runtime.lastError) { resolve({ ok: false, error: 'no_content_script' }); return; }
            resolve(resp2 || { ok: true });
          });
        });
      });
    });
  });
}

// The keyboard shortcut works with no popup open. Note that Chrome may decline
// to register Ctrl+Shift+C because DevTools claims it; inspector.js also listens
// for the chord in-page, so the gesture works either way.
if (chrome.commands && chrome.commands.onCommand) {
  chrome.commands.onCommand.addListener(function (command) {
    if (command === 'toggle-inspector') toggleInspector('toggle');
  });
}

// Relay a control message to the active tab's content script.
async function relayToActiveTab(message) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }
      chrome.tabs.sendMessage(tab.id, message, function (resp) {
        if (chrome.runtime.lastError) {
          resolve({ ok: false, error: 'no_content_script' });
        } else {
          resolve(resp || { ok: true });
        }
      });
    });
  });
}

chrome.runtime.onMessage.addListener(function (msg, _sender, sendResponse) {
  if (!msg || !msg.type) return;
  switch (msg.type) {
    case 'AB_SEND_FLOW':
      sendFlow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_CHECK':
      checkConnection().then(sendResponse);
      return true; // async
    case 'AB_LIST_WORKFLOWS':
      listWorkflows().then(sendResponse);
      return true; // async
    case 'AB_RUN_SAVED':
      runSavedWorkflow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_START':
      startLive(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_STOP':
      sendResponse(stopLive(msg.payload));
      return false;
    case 'AB_OPEN_PANEL':
      openPanel().then(sendResponse);
      return true; // async
    case 'AB_RELAY':
      relayToActiveTab(msg.message).then(sendResponse);
      return true; // async

    // ---- Element Inspector -------------------------------------------------
    // Sent by content/inspector.js when the user presses "Confirm & Add to Node".
    case 'ab-inspector-submit':
      submitElement(msg).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_SESSION':
      inspectorSession().then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_TOGGLE':
      toggleInspector(msg.desired).then(sendResponse);
      return true; // async
    case 'AB_MODE_GET':
      getBrowserMode().then(sendResponse);
      return true; // async
    case 'AB_MODE_SET':
      setBrowserMode(msg.payload).then(sendResponse);
      return true; // async

    // ---- Remote <-> Local handoff -----------------------------------------
    case 'AB_HANDOFF_PAIR':
      handoffPair(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_APPLY':
      handoffApply().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_STATUS':
      handoffStatus().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_UNPAIR':
      handoffUnpair().then(sendResponse);
      return true; // async
    default:
      return false;
  }
});
