/* ============================================================
   background.js — service worker (Step 13, extended in Step 31).
   - Performs the secure POST /run to the backend. Doing the fetch
     here (extension-privileged, with host_permissions) avoids the
     page-context CORS restrictions a content script would hit.
   - Step 31: makes the extension a thin client of the SAME backend the
     dashboard panel uses (Model A): it can list saved workflows
     (GET /workflows/:userId), run a saved workflow
     (POST /workflows/:userId/:workflowId/run), open the panel tab, and
     stream a job's live events over SSE — forwarding each event to the
     popup so it can paint per-node tick/error (mirroring Step 26).
   - Relays a few control messages from the popup to the active tab's
     content script (picker/recorder toggles).

   Settings (backend base URL, API key, userId) live in
   chrome.storage.local: ab_baseUrl, ab_apiKey, ab_userId.
   API key is never logged.

   Pure URL/parse/event logic is shared with the popup (and unit tests)
   via lib/ab-core.js — imported here as the global ABCore.
   ============================================================ */
'use strict';

// Service workers can pull in classic scripts synchronously. ab-core.js is a
// pure, DOM-free module that also runs in the popup and in vitest (one source
// of truth for URL building, list parsing and live-event mapping).
try { importScripts('lib/ab-core.js'); } catch (e) { /* ABCore optional fallback below */ }

// ab-handoff.js is the Local half of the Remote <-> Local switch. It lives HERE
// rather than in the popup on purpose: restoring a session opens N tabs and then
// reports completion, and the popup is destroyed the instant the user clicks
// away or Chrome moves focus to a new tab. A restore hosted in the popup would
// be killed mid-sequence, leaving some tabs open, nothing focused and the server
// still waiting -- exactly the "half-moved browser" state the ordering inside
// applyHandoff() is designed to avoid. The worker outlives the popup, so the
// popup only sends a message and the sequence completes regardless.
try { importScripts('lib/ab-handoff.js'); } catch (e) { /* ABHandoff optional; guarded at use */ }

// Optional, and present ONLY in the copy the server side-loads into the REMOTE
// browser (generated by src/core/InspectorExtension.ts). It is absent from the
// authored `extension/` directory and from any hand-installed copy, so the
// failure to import is the normal case for a user's own Chrome — hence a plain
// swallow rather than a warning.
try { importScripts('bootstrap.config.js'); } catch (e) { /* not a managed copy */ }

/**
 * Apply the server's bootstrap settings as DEFAULTS.
 *
 * WHY THIS EXISTS
 * ---------------
 * When the server side-loads this extension into the remote browser, the fresh
 * profile has an EMPTY `chrome.storage.local`. Without this, the popup would open
 * inside a remote desktop asking the user for the address and API token of the
 * very server that just launched the browser they are looking at — something
 * they cannot read from in there, and should not have to.
 *
 * WHY IT CAN ONLY EVER FILL IN BLANKS
 * -----------------------------------
 * Each key is written only when it is currently empty. A user who typed their own
 * base URL or key keeps it, on this launch and on every launch after — a managed
 * default that silently reverted a deliberate setting would be far worse than no
 * default at all. That is also why it is not `chrome.storage.local.set(all)`.
 */
async function applyBootstrapDefaults() {
  if (typeof AB_BOOTSTRAP === 'undefined' || !AB_BOOTSTRAP) return;
  var current = await new Promise(function (resolve) {
    chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
      resolve(s || {});
    });
  });

  var patch = {};
  if (!current.ab_baseUrl && AB_BOOTSTRAP.baseUrl) patch.ab_baseUrl = AB_BOOTSTRAP.baseUrl;
  if (!current.ab_apiKey && AB_BOOTSTRAP.apiKey) patch.ab_apiKey = AB_BOOTSTRAP.apiKey;
  if (!current.ab_userId && AB_BOOTSTRAP.userId) patch.ab_userId = AB_BOOTSTRAP.userId;
  if (!Object.keys(patch).length) return;

  await new Promise(function (resolve) {
    chrome.storage.local.set(patch, function () { resolve(); });
  });
}

// On install AND on every worker start: an MV3 service worker is killed when
// idle, and `onInstalled` does not fire again when it is revived. Running it on
// load as well is what makes the settings reliably present.
if (chrome.runtime && chrome.runtime.onInstalled) {
  chrome.runtime.onInstalled.addListener(function () {
    applyBootstrapDefaults().catch(function () { /* defaults are best-effort */ });
  });
}
var abBootstrapReady = applyBootstrapDefaults().catch(function () { /* best-effort */ });

function getSettings() {
  // Await the bootstrap before reading, so the FIRST request out of a freshly
  // seeded extension is already configured instead of failing with
  // `no_base_url` and needing a retry the user has to guess at.
  return abBootstrapReady.then(function () {
    return new Promise(function (resolve) {
      chrome.storage.local.get(['ab_baseUrl', 'ab_apiKey', 'ab_userId'], function (s) {
        resolve({
          baseUrl: (s && s.ab_baseUrl) || '',
          apiKey: (s && s.ab_apiKey) || '',
          userId: (s && s.ab_userId) || 'local'
        });
      });
    });
  });
}

// Prefer the shared ABCore.normalizeBase; keep a tiny local fallback so the
// worker still functions if importScripts ever fails.
function normalizeBase(url) {
  if (typeof ABCore !== 'undefined' && ABCore.normalizeBase) return ABCore.normalizeBase(url);
  var u = String(url || '').trim();
  if (!u) return '';
  if (!/^https?:\/\//i.test(u)) u = 'http://' + u;
  return u.replace(/\/+$/, '');
}

// Small JSON fetch helper that always returns { ok, status, data, error? }.
async function apiFetch(url, opts, apiKey) {
  var headers = Object.assign(
    { 'Content-Type': 'application/json' },
    apiKey ? { 'x-api-key': apiKey } : {},
    (opts && opts.headers) || {}
  );
  try {
    var res = await fetch(url, Object.assign({}, opts, { headers: headers }));
    var text = await res.text();
    var data;
    try { data = text ? JSON.parse(text) : null; } catch (e) { data = { raw: text }; }
    if (!res.ok) return { ok: false, error: 'http_' + res.status, status: res.status, data: data };
    return { ok: true, status: res.status, data: data };
  } catch (e) {
    return { ok: false, error: 'network', message: String((e && e.message) || e) };
  }
}

// Send the recorded steps to the backend as an inline Flow (POST /run).
async function sendFlow(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };

  var steps = Array.isArray(payload && payload.steps) ? payload.steps : [];
  if (!steps.length) return { ok: false, error: 'no_steps' };

  var body = { userId: cfg.userId || 'local', steps: steps, headless: true };
  if (payload && payload.webhookUrl) body.webhookUrl = payload.webhookUrl;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunInlineUrl)
    ? ABCore.buildRunInlineUrl(base, { wait: !!(payload && payload.wait) })
    : base + '/run';
  return apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, cfg.apiKey);
}

// Validate the API key / connectivity via GET /me. Returns data so the popup
// can resolve the canonical userId the key is bound to.
async function checkConnection() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  return apiFetch(base + '/me', { method: 'GET' }, cfg.apiKey);
}

// Step 31: list the user's saved workflows — the SAME list the panel shows.
async function listWorkflows() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var userId = cfg.userId || 'local';
  var res = await apiFetch(base + '/workflows/' + encodeURIComponent(userId), { method: 'GET' }, cfg.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.parseWorkflowList) {
    res.workflows = ABCore.parseWorkflowList(res.data);
  }
  return res;
}

// Step 31: run a saved, versioned workflow (Model B contract, shared with the
// n8n node) and return the jobId so the popup can subscribe to live events.
async function runSavedWorkflow(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var workflowId = payload && payload.workflowId;
  if (!workflowId) return { ok: false, error: 'no_workflow_id' };

  var userId = cfg.userId || 'local';
  var url = (typeof ABCore !== 'undefined' && ABCore.buildRunSavedUrl)
    ? ABCore.buildRunSavedUrl(base, userId, workflowId, { wait: !!(payload && payload.wait) })
    : base + '/workflows/' + encodeURIComponent(userId) + '/' + encodeURIComponent(workflowId) + '/run';

  var body = {};
  if (payload && payload.triggerData) body.triggerData = payload.triggerData;
  if (payload && typeof payload.headless === 'boolean') body.headless = payload.headless;

  var res = await apiFetch(url, { method: 'POST', body: JSON.stringify(body) }, cfg.apiKey);
  if (res.ok && typeof ABCore !== 'undefined' && ABCore.extractJobId) {
    res.jobId = ABCore.extractJobId(res.data);
  }
  return res;
}

// ---- Live (SSE) streaming -------------------------------------------------
// We stream a job's events here in the worker (host-privileged) and forward
// each mapped status delta to the popup via runtime messages, so the popup can
// paint tick/error per node even though EventSource cannot set headers.
var liveControllers = {}; // jobId -> AbortController

function broadcast(message) {
  try { chrome.runtime.sendMessage(message, function () { void chrome.runtime.lastError; }); } catch (e) { /* popup closed */ }
}

async function startLive(payload) {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  if (!cfg.apiKey) return { ok: false, error: 'no_api_key' };
  var jobId = payload && payload.jobId;
  if (!jobId) return { ok: false, error: 'no_job_id' };
  var userId = (payload && payload.userId) || cfg.userId || 'local';

  // stop a previous stream for the same job if any
  if (liveControllers[jobId]) { try { liveControllers[jobId].abort(); } catch (e) { /* noop */ } }
  var controller = new AbortController();
  liveControllers[jobId] = controller;

  var url = (typeof ABCore !== 'undefined' && ABCore.buildSseUrl)
    ? ABCore.buildSseUrl(base, userId, jobId, cfg.apiKey)
    : base + '/live/sse/' + encodeURIComponent(userId) + '/' + encodeURIComponent(jobId) + '?api_key=' + encodeURIComponent(cfg.apiKey);

  // Drive the SSE stream with fetch + ReadableStream (works in MV3 workers,
  // unlike EventSource which is unavailable there).
  (async function pump() {
    try {
      var res = await fetch(url, { method: 'GET', signal: controller.signal });
      if (!res.ok || !res.body) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'http_' + res.status });
        cleanupLive(jobId);
        return;
      }
      var reader = res.body.getReader();
      var decoder = new TextDecoder();
      var buf = '';
      while (true) {
        var chunk = await reader.read();
        if (chunk.done) break;
        buf += decoder.decode(chunk.value, { stream: true });
        var idx;
        // SSE frames are separated by a blank line.
        while ((idx = buf.indexOf('\n\n')) !== -1) {
          var frame = buf.slice(0, idx);
          buf = buf.slice(idx + 2);
          handleSseFrame(jobId, frame);
        }
      }
      broadcast({ type: 'AB_LIVE_END', jobId: jobId });
    } catch (e) {
      if (!controller.signal.aborted) {
        broadcast({ type: 'AB_LIVE_ERROR', jobId: jobId, error: 'network', message: String((e && e.message) || e) });
      }
    } finally {
      cleanupLive(jobId);
    }
  })();

  return { ok: true, jobId: jobId };
}

function handleSseFrame(jobId, frame) {
  // Parse the "event:" and "data:" lines of one SSE frame.
  var lines = frame.split('\n');
  var dataLines = [];
  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (line.indexOf('data:') === 0) dataLines.push(line.slice(5).trimStart());
  }
  if (!dataLines.length) return;
  var raw = dataLines.join('\n');
  var ev;
  try { ev = JSON.parse(raw); } catch (e) { return; }

  var status = (typeof ABCore !== 'undefined' && ABCore.mapLiveEventToStatus)
    ? ABCore.mapLiveEventToStatus(ev) : null;
  broadcast({ type: 'AB_LIVE_EVENT', jobId: jobId, event: ev, status: status });

  if (typeof ABCore !== 'undefined' && ABCore.isTerminalEvent && ABCore.isTerminalEvent(ev)) {
    var ctrl = liveControllers[jobId];
    if (ctrl) { try { ctrl.abort(); } catch (e) { /* noop */ } }
  }
}

function cleanupLive(jobId) {
  if (liveControllers[jobId]) { delete liveControllers[jobId]; }
}

function stopLive(payload) {
  var jobId = payload && payload.jobId;
  if (jobId && liveControllers[jobId]) {
    try { liveControllers[jobId].abort(); } catch (e) { /* noop */ }
    cleanupLive(jobId);
  }
  return { ok: true };
}

// Step 31: open (or focus) the dashboard panel — the SAME UI the extension is
// a thin client of.
async function openPanel() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { ok: false, error: 'no_base_url' };
  var url = (typeof ABCore !== 'undefined' && ABCore.buildPanelUrl) ? ABCore.buildPanelUrl(base) : base + '/';
  return new Promise(function (resolve) {
    chrome.tabs.create({ url: url }, function (tab) {
      if (chrome.runtime.lastError) { resolve({ ok: false, error: 'open_failed' }); return; }
      resolve({ ok: true, tabId: tab && tab.id });
    });
  });
}

/* ============================================================
   ELEMENT INSPECTOR

   The content script cannot POST the pick itself: a fetch from page context is
   subject to the page's CSP and to CORS against the backend origin. The worker
   holds host_permissions, so the request belongs here — same reason sendFlow
   lives here.

   THE DESTINATION IS A TARGET FIELD, AND IT IS PAIRED ONCE
   -------------------------------------------------------
   This worker used to mint its own `ext-…` session id and submit picks under it.
   The dashboard claimed nodes under a per-TAB `ui-…` id, and the server compared
   the two for equality — two independently generated strings, so every pick was
   refused. The id was then read back from the server purely to satisfy the
   comparison, a round trip that carried no information: the value sent was the
   value the server had handed over moments earlier.

   That whole mechanism is gone. The destination is now a Target Field the
   project registers, addressed by `targetFieldId`, and this extension is bound
   to it ONCE by typing an Authorization Code. After that, ordinary sends carry
   only the API key and the id — no session, no echo, nothing to keep in sync.

   The extension therefore stores exactly one new thing: which Target Field it is
   currently sending to. That is a user CHOICE, so it is persisted rather than
   re-derived, and it survives worker restarts (MV3 kills workers aggressively).
   ============================================================ */

// Resolve base + key once for the inspector calls, with the same explicit
// error keys the popup already knows how to render.
async function inspectorContext() {
  var cfg = await getSettings();
  var base = normalizeBase(cfg.baseUrl);
  if (!base) return { error: 'no_base_url' };
  if (!cfg.apiKey) return { error: 'no_api_key' };
  return { base: base, apiKey: cfg.apiKey, userId: cfg.userId || 'local' };
}

/** Which Target Field this extension is currently sending to, if any. */
function getTargetFieldId() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_targetFieldId'], function (s) {
      resolve((s && s.ab_targetFieldId) || '');
    });
  });
}

function setTargetFieldId(id) {
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_targetFieldId: id || '' }, function () { resolve(id || ''); });
  });
}

/**
 * The STABLE identity of the field this extension is paired with.
 *
 * Stored ALONGSIDE the address, not instead of it, because the two have
 * different lifetimes and answer different questions:
 *
 *   ab_targetFieldId  — the ADDRESS. Re-minted whenever the node is re-opened,
 *                       expires in hours. Says WHERE a pick should be sent.
 *   ab_pairingKey     — the IDENTITY. Derived from workflow+node+field, expires
 *                       in days. Says WHETHER this extension is trusted for
 *                       that field at all.
 *
 * Keeping only the address is what used to make pairing look temporary: the
 * address died on the next NDV open, and with nothing durable stored the popup
 * had to report "not paired" and the operator was asked for another code. The
 * requirement is explicit that this must not happen:
 *
 *   «دفعات بعد برای همان Extension و همان Target Field، دیگر نیازی به
 *    Authorization Code جدید نیست.»
 */
function getPairingKey() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_pairingKey'], function (s) {
      resolve((s && s.ab_pairingKey) || '');
    });
  });
}

function setPairingKey(key) {
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_pairingKey: key || '' }, function () { resolve(key || ''); });
  });
}

/**
 * Which BROWSER ENVIRONMENT the field this extension is paired with was
 * targeted in — 'local' or 'remote'.
 *
 * Recorded so the popup can state it rather than leave the operator guessing,
 * and read from the SERVER's target record, never asserted by the extension.
 * It is a third, separate concept from both of the ids above and from the
 * automation Browser Mode:
 *
 *   Browser Environment = LOCAL / REMOTE   (which browser the pick happens in)
 *   Session / Handoff   = as_… remote infra (not involved here at all)
 *   targetFieldId       = the destination   (where the value lands)
 *
 * The popup's CONNECTION tab shows a local/remote pair too, but that is derived
 * from whether the BACKEND URL is loopback — where the server is, not which
 * browser is doing the targeting. Conflating them is the confusion this field
 * exists to end.
 */
function getTargetEnvironment() {
  return new Promise(function (resolve) {
    chrome.storage.local.get(['ab_targetEnvironment'], function (s) {
      resolve((s && s.ab_targetEnvironment) || '');
    });
  });
}

function setTargetEnvironment(env) {
  var v = (env === 'local' || env === 'remote') ? env : '';
  return new Promise(function (resolve) {
    chrome.storage.local.set({ ab_targetEnvironment: v }, function () { resolve(v); });
  });
}

/**
 * What is this extension attached to — which mode, which fields are open, and
 * which of them may it write to?
 *
 * Asked when the popup opens, so the user sees the answer before picking rather
 * than discovering it from a failed send. `authorized` comes back scoped to THIS
 * API key, so the popup can show "connected to this Field" truthfully instead of
 * listing fields the extension cannot actually reach.
 */
async function inspectorSession() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var res = await apiFetch(ctx.base + '/inspector/session', { method: 'GET' }, ctx.apiKey);
  var data = (res && res.data) || {};
  var chosen = await getTargetFieldId();

  var authorized = data.authorized || [];
  var isAuthorized = authorized.some(function (b) { return b.targetFieldId === chosen; });

  res.targetFieldId = chosen;
  res.authorized = isAuthorized;
  // The full record for the DESTINATION panel: node name, field name, label.
  var target = (data.targets || []).filter(function (t) {
    return t.targetFieldId === chosen;
  })[0] || null;
  res.target = target;

  // ── The durable half of the answer ───────────────────────────────────────
  //
  // The stored pairing key is preferred over the live target's, because the
  // point of a pairing is that it outlives the address: when the dashboard has
  // not re-registered the field yet, `target` is null and the address is stale,
  // yet the operator must still be told they are paired and will NOT be asked
  // for another code.
  var storedKey = await getPairingKey();
  var pairingKey = storedKey || (target && target.pairingKey) || '';
  var pairings = data.pairings || [];
  res.pairingKey = pairingKey;
  res.paired = !!pairingKey && pairings.some(function (p) {
    return p && p.pairingKey === pairingKey;
  });

  // Environment is taken from the SERVER's target record — the extension does
  // not get to assert which browser it is. The stored value is only a fallback
  // for when the field is not currently registered.
  var env = (target && target.environment) || (await getTargetEnvironment());
  res.environment = (env === 'local' || env === 'remote') ? env : '';
  if (target && target.environment) await setTargetEnvironment(target.environment);

  // A pairing the server no longer holds must not keep being displayed: the
  // operator would be told no code is needed and then be refused on send.
  if (pairingKey && !res.paired && pairings.length) await setPairingKey('');
  return res;
}

/**
 * Redeem an Authorization Code — the one-time pairing step.
 *
 * The target is decided by the CODE, server-side. This function deliberately
 * does not send a `targetFieldId`: «The Extension must NEVER be able to choose
 * an arbitrary Target Field.» What comes back is the field the code was scoped
 * to, and THAT is what gets stored.
 */
async function inspectorPair(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var code = String((payload && payload.code) || '').trim();
  if (!code) return { ok: false, reason: 'INVALID_AUTHORIZATION_CODE', error: 'Enter the Authorization Code.' };

  var res = await apiFetch(
    ctx.base + '/inspector/pair',
    { method: 'POST', body: JSON.stringify({ code: code }) },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'The authorization code was refused.'
    };
  }

  var target = data.target || null;
  var id = (data.binding && data.binding.targetFieldId) || (target && target.targetFieldId) || '';
  await setTargetFieldId(id);

  // Store the DURABLE identity too, not just the address.
  //
  // This is the line that makes "no second code" real on the extension side.
  // The address in `ab_targetFieldId` dies with the next NDV open; the pairing
  // key does not, so on the next visit to the SAME field the popup can say
  // "already paired" and the dashboard's chooser skips the code entirely.
  // Both come from the SERVER's response — the extension never invents either,
  // because «The Extension must NEVER be able to choose an arbitrary Target
  // Field» applies just as much to the stable id as to the address.
  var pairingKey = (data.binding && data.binding.pairingKey) || (target && target.pairingKey) || '';
  await setPairingKey(pairingKey);

  var env = (target && target.environment) || '';
  await setTargetEnvironment(env);

  return {
    ok: true,
    targetFieldId: id,
    pairingKey: pairingKey,
    environment: env,
    target: target,
  };
}

/**
 * Forget the pairing locally.
 *
 * Clears the durable key as well as the address — otherwise the popup would go
 * on reporting "paired" for a field this extension has deliberately let go of,
 * and the operator would never be offered the code that would reconnect it.
 * The server keeps its own record until the dashboard's explicit
 * `/inspector/targeting/unpair`; this is the extension's local half.
 */
async function inspectorUnpair() {
  await setTargetFieldId('');
  await setPairingKey('');
  await setTargetEnvironment('');
  return { ok: true };
}

/* ============================================================
   REMOTE TARGETING CONSENT
   ============================================================

   WHY THIS EXISTS

   The browser running on the server is, from this extension's point of view, an
   ordinary LOCAL browser. It loads this same code, and it addresses a submit
   with `ab_targetFieldId` out of chrome.storage.local.

   Until now the ONLY writer of that value was inspectorPair() — redeeming an
   Authorization Code. But REMOTE deliberately never issues a code, by explicit
   requirement. So on the remote path the value stayed empty, submitElement()
   refused locally with TARGET_NOT_AUTHORIZED before any HTTP request was made,
   and the operator saw:

     «ظاهرا نمیدونه به کدوم فیلد باید ارسال بشه» — Connection failed: network

   The server had granted a binding. Nothing had ever told the CLIENT which field
   it was for.

   WHY A PROMPT AND NOT AN AUTO-FILL

   The obvious shortcut is to have the extension ask "what is my current target?"
   and adopt the answer. That was rejected: with two nodes open there IS no
   single current target, and picking the most recent silently means a pick lands
   in the node the operator is no longer looking at, WITH a success message. That
   is strictly worse than the refusal it replaces, because a refusal is visible.
   It also breaks the standing rule «The Extension must NEVER be able to choose
   an arbitrary Target Field» — an extension that adopts whatever a list contains
   has chosen.

   So the server ASKS, naming the node and the field, and the human answers. A
   consent and a code are the same security object — one-time, server-issued,
   expiring, single-target, completable only by a person. The consent is merely
   addressed to a browser the server can already reach, so it can be DELIVERED
   instead of TRANSCRIBED. Approval is what attaches the destination, which is
   why the reply to a decision is stored exactly the way a redeemed code is.
   ============================================================ */

/**
 * What is this browser being asked to confirm?
 *
 * Returns the human-readable questions ONLY. The server withholds the target
 * address from this list on purpose (see ConsentPrompt in
 * src/core/RemoteTargetConsent.ts): if the address were here, this function
 * could store it and skip the prompt, which is the one thing the handshake
 * exists to prevent.
 */
async function consentList() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error, requests: [] };

  var res = await apiFetch(ctx.base + '/inspector/consent', { method: 'GET' }, ctx.apiKey);
  var data = (res && res.data) || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'Could not ask the server what is pending.',
      requests: [],
    };
  }
  return { ok: true, count: data.count || 0, requests: data.requests || [] };
}

/**
 * The human pressed Allow (or Deny).
 *
 * Sends a `consentId` and a boolean — never a target. The destination comes back
 * FROM the server, decided before the prompt was ever raised, and storing it is
 * the line that makes the reported failure go away: it is the write to
 * `ab_targetFieldId` that REMOTE never had.
 *
 * Deliberately mirrors inspectorPair() field for field, including the durable
 * pairing key and the environment, because a consent-granted pairing must be
 * exactly as durable as a code-granted one. If it were not, the operator would
 * be re-prompted on every NDV open and we would have replaced "type a code every
 * time" with "click Allow every time" — a different spelling of the same defect.
 */
async function consentDecide(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var consentId = String((payload && payload.consentId) || '').trim();
  if (!consentId) {
    return { ok: false, reason: 'consent_not_found', error: 'Nothing to answer.' };
  }
  // Explicitly boolean: `approve: undefined` must never read as approval.
  var approve = (payload && payload.approve) === true;

  var res = await apiFetch(
    ctx.base + '/inspector/consent/decide',
    { method: 'POST', body: JSON.stringify({ consentId: consentId, approve: approve }) },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'That request could not be answered.',
    };
  }

  // Denied: the server attached nothing, so neither do we. Anything already
  // paired is left alone — declining a NEW field must not disconnect the field
  // this browser is currently working on.
  if (!data.approved) {
    return { ok: true, approved: false, consentId: consentId };
  }

  var target = data.target || null;
  var id = (data.binding && data.binding.targetFieldId) || data.targetFieldId
    || (target && target.targetFieldId) || '';
  await setTargetFieldId(id);

  var pairingKey = (data.binding && data.binding.pairingKey) || data.pairingKey
    || (target && target.pairingKey) || '';
  await setPairingKey(pairingKey);

  var env = (target && target.environment) || 'remote';
  await setTargetEnvironment(env);

  return {
    ok: true,
    approved: true,
    consentId: consentId,
    targetFieldId: id,
    pairingKey: pairingKey,
    environment: env,
    target: target,
  };
}

/**
 * Deliver ONE confirmed attribute to the paired Target Field.
 *
 * §21: «the system sends exactly ONE Radio-selected value», so the payload
 * carries `sendAttribute` (the radio) and `displayAttributes` (the checkboxes,
 * which affect display only). The server recomputes the value from the element
 * it receives, so the `value` here is advisory.
 *
 * Refusals pass the backend's §27 code and sentence through UNCHANGED, because
 * "this Inspector is not authorized for that Field" is a fixable problem and a
 * generic failure message hides the fix.
 */
async function submitElement(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };

  var element = payload && payload.element;
  if (!element) return { ok: false, error: 'no_element' };

  // §22.5 — a radio must be selected. Refused here rather than sent, because the
  // only possible answer is a 409 and the message is the same either way.
  var send = (payload && payload.sendAttribute) || null;
  var attrName = send && String(send.name || '').trim();
  if (!attrName) {
    return {
      ok: false,
      reason: 'ATTRIBUTE_SEND_FAILED',
      error: 'Select one attribute to send.'
    };
  }

  // The destination must have been paired. Refusing locally saves a round trip
  // and names the actual fix.
  var targetFieldId = await getTargetFieldId();
  if (!targetFieldId) {
    return {
      ok: false,
      reason: 'TARGET_NOT_AUTHORIZED',
      error: 'This Inspector is not connected to a Field. Enter an Authorization Code first.'
    };
  }

  var res = await apiFetch(
    ctx.base + '/inspector/element',
    {
      method: 'POST',
      body: JSON.stringify({
        targetFieldId: targetFieldId,
        element: element,
        displayAttributes: (payload && payload.displayAttributes) || [],
        sendAttribute: { name: attrName, value: send.value }
      })
    },
    ctx.apiKey
  );

  var data = res.data || {};
  if (!res.ok) {
    return {
      ok: false,
      reason: data.reason || res.error,
      error: data.error || res.message || 'The element could not be delivered.',
      targets: data.targets || []
    };
  }

  // §24: the confirmation NAMES the field, the attribute and the value — that is
  // what proves the value did not silently go somewhere else.
  return {
    ok: true,
    node: data.nodeName || '',
    field: data.fieldName || '',
    targetFieldId: data.targetFieldId || targetFieldId,
    attribute: data.attribute || attrName,
    value: data.value || '',
    delivery: data.delivery || null
  };
}

/** Read the current browser mode (Remote / Local) for the popup's indicator. */
async function getBrowserMode() {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  return apiFetch(ctx.base + '/browser-mode', { method: 'GET' }, ctx.apiKey);
}

/** Switch mode from the extension. 409 means the backend refused, with a note. */
async function setBrowserMode(payload) {
  var ctx = await inspectorContext();
  if (ctx.error) return { ok: false, error: ctx.error };
  var mode = payload && payload.mode;
  if (!mode) return { ok: false, error: 'no_mode' };

  var res = await apiFetch(
    ctx.base + '/browser-mode',
    { method: 'POST', body: JSON.stringify({ mode: mode }) },
    ctx.apiKey
  );
  var data = res.data || {};
  if (!res.ok) {
    return { ok: false, reason: data.note || res.error, error: data.error || 'Could not switch mode.', data: data };
  }
  return { ok: true, data: data };
}

// ════════════════════════════════════════════════════════════════
// Remote -> Local handoff
//
// Thin wrappers over lib/ab-handoff.js. The base URL is resolved from settings
// here rather than passed in from the popup, so the extension can only ever pair
// with the backend it is configured for -- a code typed into the wrong window
// cannot redirect it somewhere else.
//
// NOTE these deliberately do NOT require an API key, unlike every other call in
// this worker. The whole point of the pairing code is that the extension joins a
// session WITHOUT holding the key that controls the entire instance, so demanding
// one here would defeat the security model and also break the realistic case:
// a user installing the extension for the first time has a code but no key.
// ════════════════════════════════════════════════════════════════

function handoffAvailable() {
  return (typeof ABHandoff !== 'undefined') && ABHandoff;
}

async function handoffBase() {
  var cfg = await getSettings();
  return normalizeBase(cfg.baseUrl);
}

async function handoffPair(payload) {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  if (!base) {
    return {
      ok: false,
      reason: 'no_base_url',
      error: 'Set the backend Base URL in this popup first, then enter the code.'
    };
  }
  var res = await ABHandoff.pairWithCode(base, payload && payload.code);
  return res;
}

async function handoffApply() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  var base = await handoffBase();
  return ABHandoff.applyHandoff({ baseUrl: base });
}

async function handoffStatus() {
  if (!handoffAvailable()) return { ok: false, paired: false, error: 'Handoff module failed to load.' };
  var s = await ABHandoff.status();
  return Object.assign({ ok: true }, s);
}

async function handoffUnpair() {
  if (!handoffAvailable()) return { ok: false, error: 'Handoff module failed to load.' };
  await ABHandoff.clearPairing();
  return { ok: true };
}

/**
 * Toggle the picker in the active tab.
 *
 * The content script is asked first; if it is not there (a tab opened before
 * the extension was installed, or reloaded) it is injected on the spot, so the
 * user is never told to reload the page.
 */
async function toggleInspector(desired) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }

      var type = desired === 'stop' ? 'ab-inspector-stop' : 'ab-inspector-start';
      chrome.tabs.sendMessage(tab.id, { type: type }, function (resp) {
        if (!chrome.runtime.lastError) { resolve(resp || { ok: true }); return; }
        if (!chrome.scripting || !chrome.scripting.executeScript) {
          resolve({ ok: false, error: 'no_content_script' });
          return;
        }
        // Same file order as the manifest: extraction core and selectors must
        // exist before inspector.js runs.
        chrome.scripting.executeScript({
          target: { tabId: tab.id },
          files: ['lib/ab-inspect.js', 'content/selector.js', 'content/inspector.js']
        }, function () {
          if (chrome.runtime.lastError) {
            resolve({ ok: false, error: 'inject_failed', message: chrome.runtime.lastError.message });
            return;
          }
          chrome.tabs.sendMessage(tab.id, { type: type }, function (resp2) {
            if (chrome.runtime.lastError) { resolve({ ok: false, error: 'no_content_script' }); return; }
            resolve(resp2 || { ok: true });
          });
        });
      });
    });
  });
}

// The keyboard shortcut works with no popup open. Note that Chrome may decline
// to register Ctrl+Shift+C because DevTools claims it; inspector.js also listens
// for the chord in-page, so the gesture works either way.
if (chrome.commands && chrome.commands.onCommand) {
  chrome.commands.onCommand.addListener(function (command) {
    if (command === 'toggle-inspector') toggleInspector('toggle');
  });
}

// Relay a control message to the active tab's content script.
async function relayToActiveTab(message) {
  return new Promise(function (resolve) {
    chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
      var tab = tabs && tabs[0];
      if (!tab || tab.id == null) { resolve({ ok: false, error: 'no_active_tab' }); return; }
      chrome.tabs.sendMessage(tab.id, message, function (resp) {
        if (chrome.runtime.lastError) {
          resolve({ ok: false, error: 'no_content_script' });
        } else {
          resolve(resp || { ok: true });
        }
      });
    });
  });
}

chrome.runtime.onMessage.addListener(function (msg, _sender, sendResponse) {
  if (!msg || !msg.type) return;
  switch (msg.type) {
    case 'AB_SEND_FLOW':
      sendFlow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_CHECK':
      checkConnection().then(sendResponse);
      return true; // async
    case 'AB_LIST_WORKFLOWS':
      listWorkflows().then(sendResponse);
      return true; // async
    case 'AB_RUN_SAVED':
      runSavedWorkflow(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_START':
      startLive(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_LIVE_STOP':
      sendResponse(stopLive(msg.payload));
      return false;
    case 'AB_OPEN_PANEL':
      openPanel().then(sendResponse);
      return true; // async
    case 'AB_RELAY':
      relayToActiveTab(msg.message).then(sendResponse);
      return true; // async

    // ---- Element Inspector -------------------------------------------------
    // Sent by content/inspector.js when the user presses "Confirm & Add to Node".
    case 'ab-inspector-submit':
      submitElement(msg).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_SESSION':
      inspectorSession().then(sendResponse);
      return true; // async
    // One-time pairing. Distinct from AB_HANDOFF_PAIR below: that code binds a
    // BROWSER SESSION, this one binds a TARGET FIELD. Two subsystems, two codes,
    // and unpairing either must leave the other alone.
    case 'AB_INSPECTOR_PAIR':
      inspectorPair(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_UNPAIR':
      inspectorUnpair().then(sendResponse);
      return true; // async
    case 'AB_INSPECTOR_TOGGLE':
      toggleInspector(msg.desired).then(sendResponse);
      return true; // async

    // ---- Remote targeting consent -----------------------------------------
    // The REMOTE counterpart of AB_INSPECTOR_PAIR. Same outcome — a stored
    // target — reached by answering a question the server delivered instead of
    // by transcribing a code, because on this path there is no code to type.
    case 'AB_CONSENT_LIST':
      consentList().then(sendResponse);
      return true; // async
    case 'AB_CONSENT_DECIDE':
      consentDecide(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_MODE_GET':
      getBrowserMode().then(sendResponse);
      return true; // async
    case 'AB_MODE_SET':
      setBrowserMode(msg.payload).then(sendResponse);
      return true; // async

    // ---- Remote <-> Local handoff -----------------------------------------
    case 'AB_HANDOFF_PAIR':
      handoffPair(msg.payload).then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_APPLY':
      handoffApply().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_STATUS':
      handoffStatus().then(sendResponse);
      return true; // async
    case 'AB_HANDOFF_UNPAIR':
      handoffUnpair().then(sendResponse);
      return true; // async
    default:
      return false;
  }
});
